// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/AlloService.proto

package com.widogame.minegamedataserver.grpc;

public final class AlloServiceOuterClass {
  private AlloServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AlloRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AlloService.AlloRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code AlloService.AlloRequest}
   */
  public static final class AlloRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AlloService.AlloRequest)
      AlloRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AlloRequest.newBuilder() to construct.
    private AlloRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AlloRequest() {
      key_ = "";
      value_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AlloRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AlloRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.internal_static_AlloService_AlloRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.internal_static_AlloService_AlloRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest.class, com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest)) {
        return super.equals(obj);
      }
      com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest other = (com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AlloService.AlloRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AlloService.AlloRequest)
        com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.internal_static_AlloService_AlloRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.internal_static_AlloService_AlloRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest.class, com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest.Builder.class);
      }

      // Construct using com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        key_ = "";

        value_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.internal_static_AlloService_AlloRequest_descriptor;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest getDefaultInstanceForType() {
        return com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest build() {
        com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest buildPartial() {
        com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest result = new com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest(this);
        result.key_ = key_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest) {
          return mergeFrom((com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest other) {
        if (other == com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AlloService.AlloRequest)
    }

    // @@protoc_insertion_point(class_scope:AlloService.AlloRequest)
    private static final com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest();
    }

    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AlloRequest>
        PARSER = new com.google.protobuf.AbstractParser<AlloRequest>() {
      @java.lang.Override
      public AlloRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlloRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AlloRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AlloRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AlloResponesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AlloService.AlloRespones)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string connTcp = 1;</code>
     * @return The connTcp.
     */
    java.lang.String getConnTcp();
    /**
     * <code>string connTcp = 1;</code>
     * @return The bytes for connTcp.
     */
    com.google.protobuf.ByteString
        getConnTcpBytes();

    /**
     * <code>string connUdp = 2;</code>
     * @return The connUdp.
     */
    java.lang.String getConnUdp();
    /**
     * <code>string connUdp = 2;</code>
     * @return The bytes for connUdp.
     */
    com.google.protobuf.ByteString
        getConnUdpBytes();
  }
  /**
   * Protobuf type {@code AlloService.AlloRespones}
   */
  public static final class AlloRespones extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AlloService.AlloRespones)
      AlloResponesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AlloRespones.newBuilder() to construct.
    private AlloRespones(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AlloRespones() {
      connTcp_ = "";
      connUdp_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AlloRespones();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AlloRespones(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              connTcp_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              connUdp_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.internal_static_AlloService_AlloRespones_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.internal_static_AlloService_AlloRespones_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones.class, com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones.Builder.class);
    }

    public static final int CONNTCP_FIELD_NUMBER = 1;
    private volatile java.lang.Object connTcp_;
    /**
     * <code>string connTcp = 1;</code>
     * @return The connTcp.
     */
    @java.lang.Override
    public java.lang.String getConnTcp() {
      java.lang.Object ref = connTcp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connTcp_ = s;
        return s;
      }
    }
    /**
     * <code>string connTcp = 1;</code>
     * @return The bytes for connTcp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConnTcpBytes() {
      java.lang.Object ref = connTcp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connTcp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONNUDP_FIELD_NUMBER = 2;
    private volatile java.lang.Object connUdp_;
    /**
     * <code>string connUdp = 2;</code>
     * @return The connUdp.
     */
    @java.lang.Override
    public java.lang.String getConnUdp() {
      java.lang.Object ref = connUdp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connUdp_ = s;
        return s;
      }
    }
    /**
     * <code>string connUdp = 2;</code>
     * @return The bytes for connUdp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConnUdpBytes() {
      java.lang.Object ref = connUdp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connUdp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connTcp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, connTcp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connUdp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, connUdp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connTcp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, connTcp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connUdp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, connUdp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones)) {
        return super.equals(obj);
      }
      com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones other = (com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones) obj;

      if (!getConnTcp()
          .equals(other.getConnTcp())) return false;
      if (!getConnUdp()
          .equals(other.getConnUdp())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONNTCP_FIELD_NUMBER;
      hash = (53 * hash) + getConnTcp().hashCode();
      hash = (37 * hash) + CONNUDP_FIELD_NUMBER;
      hash = (53 * hash) + getConnUdp().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AlloService.AlloRespones}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AlloService.AlloRespones)
        com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloResponesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.internal_static_AlloService_AlloRespones_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.internal_static_AlloService_AlloRespones_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones.class, com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones.Builder.class);
      }

      // Construct using com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        connTcp_ = "";

        connUdp_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.internal_static_AlloService_AlloRespones_descriptor;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones getDefaultInstanceForType() {
        return com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones.getDefaultInstance();
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones build() {
        com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones buildPartial() {
        com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones result = new com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones(this);
        result.connTcp_ = connTcp_;
        result.connUdp_ = connUdp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones) {
          return mergeFrom((com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones other) {
        if (other == com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones.getDefaultInstance()) return this;
        if (!other.getConnTcp().isEmpty()) {
          connTcp_ = other.connTcp_;
          onChanged();
        }
        if (!other.getConnUdp().isEmpty()) {
          connUdp_ = other.connUdp_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object connTcp_ = "";
      /**
       * <code>string connTcp = 1;</code>
       * @return The connTcp.
       */
      public java.lang.String getConnTcp() {
        java.lang.Object ref = connTcp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          connTcp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string connTcp = 1;</code>
       * @return The bytes for connTcp.
       */
      public com.google.protobuf.ByteString
          getConnTcpBytes() {
        java.lang.Object ref = connTcp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          connTcp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string connTcp = 1;</code>
       * @param value The connTcp to set.
       * @return This builder for chaining.
       */
      public Builder setConnTcp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        connTcp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string connTcp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnTcp() {
        
        connTcp_ = getDefaultInstance().getConnTcp();
        onChanged();
        return this;
      }
      /**
       * <code>string connTcp = 1;</code>
       * @param value The bytes for connTcp to set.
       * @return This builder for chaining.
       */
      public Builder setConnTcpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        connTcp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object connUdp_ = "";
      /**
       * <code>string connUdp = 2;</code>
       * @return The connUdp.
       */
      public java.lang.String getConnUdp() {
        java.lang.Object ref = connUdp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          connUdp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string connUdp = 2;</code>
       * @return The bytes for connUdp.
       */
      public com.google.protobuf.ByteString
          getConnUdpBytes() {
        java.lang.Object ref = connUdp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          connUdp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string connUdp = 2;</code>
       * @param value The connUdp to set.
       * @return This builder for chaining.
       */
      public Builder setConnUdp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        connUdp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string connUdp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnUdp() {
        
        connUdp_ = getDefaultInstance().getConnUdp();
        onChanged();
        return this;
      }
      /**
       * <code>string connUdp = 2;</code>
       * @param value The bytes for connUdp to set.
       * @return This builder for chaining.
       */
      public Builder setConnUdpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        connUdp_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AlloService.AlloRespones)
    }

    // @@protoc_insertion_point(class_scope:AlloService.AlloRespones)
    private static final com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones();
    }

    public static com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AlloRespones>
        PARSER = new com.google.protobuf.AbstractParser<AlloRespones>() {
      @java.lang.Override
      public AlloRespones parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlloRespones(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AlloRespones> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AlloRespones> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.AlloServiceOuterClass.AlloRespones getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AlloService_AlloRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AlloService_AlloRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AlloService_AlloRespones_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AlloService_AlloRespones_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031service/AlloService.proto\022\013AlloService" +
      "\")\n\013AlloRequest\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t\"0\n\014AlloRespones\022\017\n\007connTcp\030\001 \001(\t\022\017\n\007" +
      "connUdp\030\002 \001(\t2P\n\013AlloService\022A\n\010Allocate" +
      "\022\030.AlloService.AlloRequest\032\031.AlloService" +
      ".AlloRespones\"\000BW\n$com.widogame.minegame" +
      "dataserver.grpcZ\010./allopb\252\002$com.widogame" +
      ".minegamedataserver.grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AlloService_AlloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AlloService_AlloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AlloService_AlloRequest_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_AlloService_AlloRespones_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AlloService_AlloRespones_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AlloService_AlloRespones_descriptor,
        new java.lang.String[] { "ConnTcp", "ConnUdp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
