// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/CharacterMessage.proto

package com.widogame.minegamedataserver.grpc;

public final class CharacterMessage {
  private CharacterMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InventoryCharacterResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InventoryCharacterResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>.Stats stats = 2;</code>
     * @return Whether the stats field is set.
     */
    boolean hasStats();
    /**
     * <code>.Stats stats = 2;</code>
     * @return The stats.
     */
    com.widogame.minegamedataserver.grpc.CharacterMessage.Stats getStats();
    /**
     * <code>.Stats stats = 2;</code>
     */
    com.widogame.minegamedataserver.grpc.CharacterMessage.StatsOrBuilder getStatsOrBuilder();

    /**
     * <code>int64 adn = 3;</code>
     * @return The adn.
     */
    long getAdn();

    /**
     * <code>int64 ownerId = 4;</code>
     * @return The ownerId.
     */
    long getOwnerId();
  }
  /**
   * Protobuf type {@code InventoryCharacterResult}
   */
  public static final class InventoryCharacterResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InventoryCharacterResult)
      InventoryCharacterResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InventoryCharacterResult.newBuilder() to construct.
    private InventoryCharacterResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InventoryCharacterResult() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InventoryCharacterResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InventoryCharacterResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.Builder subBuilder = null;
              if (stats_ != null) {
                subBuilder = stats_.toBuilder();
              }
              stats_ = input.readMessage(com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stats_);
                stats_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              adn_ = input.readInt64();
              break;
            }
            case 32: {

              ownerId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_InventoryCharacterResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_InventoryCharacterResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult.class, com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int STATS_FIELD_NUMBER = 2;
    private com.widogame.minegamedataserver.grpc.CharacterMessage.Stats stats_;
    /**
     * <code>.Stats stats = 2;</code>
     * @return Whether the stats field is set.
     */
    @java.lang.Override
    public boolean hasStats() {
      return stats_ != null;
    }
    /**
     * <code>.Stats stats = 2;</code>
     * @return The stats.
     */
    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.CharacterMessage.Stats getStats() {
      return stats_ == null ? com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.getDefaultInstance() : stats_;
    }
    /**
     * <code>.Stats stats = 2;</code>
     */
    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.CharacterMessage.StatsOrBuilder getStatsOrBuilder() {
      return getStats();
    }

    public static final int ADN_FIELD_NUMBER = 3;
    private long adn_;
    /**
     * <code>int64 adn = 3;</code>
     * @return The adn.
     */
    @java.lang.Override
    public long getAdn() {
      return adn_;
    }

    public static final int OWNERID_FIELD_NUMBER = 4;
    private long ownerId_;
    /**
     * <code>int64 ownerId = 4;</code>
     * @return The ownerId.
     */
    @java.lang.Override
    public long getOwnerId() {
      return ownerId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (stats_ != null) {
        output.writeMessage(2, getStats());
      }
      if (adn_ != 0L) {
        output.writeInt64(3, adn_);
      }
      if (ownerId_ != 0L) {
        output.writeInt64(4, ownerId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (stats_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStats());
      }
      if (adn_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, adn_);
      }
      if (ownerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, ownerId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult)) {
        return super.equals(obj);
      }
      com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult other = (com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult) obj;

      if (getId()
          != other.getId()) return false;
      if (hasStats() != other.hasStats()) return false;
      if (hasStats()) {
        if (!getStats()
            .equals(other.getStats())) return false;
      }
      if (getAdn()
          != other.getAdn()) return false;
      if (getOwnerId()
          != other.getOwnerId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (hasStats()) {
        hash = (37 * hash) + STATS_FIELD_NUMBER;
        hash = (53 * hash) + getStats().hashCode();
      }
      hash = (37 * hash) + ADN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAdn());
      hash = (37 * hash) + OWNERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOwnerId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InventoryCharacterResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InventoryCharacterResult)
        com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_InventoryCharacterResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_InventoryCharacterResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult.class, com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult.Builder.class);
      }

      // Construct using com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        if (statsBuilder_ == null) {
          stats_ = null;
        } else {
          stats_ = null;
          statsBuilder_ = null;
        }
        adn_ = 0L;

        ownerId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_InventoryCharacterResult_descriptor;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult getDefaultInstanceForType() {
        return com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult.getDefaultInstance();
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult build() {
        com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult buildPartial() {
        com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult result = new com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult(this);
        result.id_ = id_;
        if (statsBuilder_ == null) {
          result.stats_ = stats_;
        } else {
          result.stats_ = statsBuilder_.build();
        }
        result.adn_ = adn_;
        result.ownerId_ = ownerId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult) {
          return mergeFrom((com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult other) {
        if (other == com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.hasStats()) {
          mergeStats(other.getStats());
        }
        if (other.getAdn() != 0L) {
          setAdn(other.getAdn());
        }
        if (other.getOwnerId() != 0L) {
          setOwnerId(other.getOwnerId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private com.widogame.minegamedataserver.grpc.CharacterMessage.Stats stats_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.widogame.minegamedataserver.grpc.CharacterMessage.Stats, com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.Builder, com.widogame.minegamedataserver.grpc.CharacterMessage.StatsOrBuilder> statsBuilder_;
      /**
       * <code>.Stats stats = 2;</code>
       * @return Whether the stats field is set.
       */
      public boolean hasStats() {
        return statsBuilder_ != null || stats_ != null;
      }
      /**
       * <code>.Stats stats = 2;</code>
       * @return The stats.
       */
      public com.widogame.minegamedataserver.grpc.CharacterMessage.Stats getStats() {
        if (statsBuilder_ == null) {
          return stats_ == null ? com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.getDefaultInstance() : stats_;
        } else {
          return statsBuilder_.getMessage();
        }
      }
      /**
       * <code>.Stats stats = 2;</code>
       */
      public Builder setStats(com.widogame.minegamedataserver.grpc.CharacterMessage.Stats value) {
        if (statsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stats_ = value;
          onChanged();
        } else {
          statsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Stats stats = 2;</code>
       */
      public Builder setStats(
          com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.Builder builderForValue) {
        if (statsBuilder_ == null) {
          stats_ = builderForValue.build();
          onChanged();
        } else {
          statsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Stats stats = 2;</code>
       */
      public Builder mergeStats(com.widogame.minegamedataserver.grpc.CharacterMessage.Stats value) {
        if (statsBuilder_ == null) {
          if (stats_ != null) {
            stats_ =
              com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.newBuilder(stats_).mergeFrom(value).buildPartial();
          } else {
            stats_ = value;
          }
          onChanged();
        } else {
          statsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Stats stats = 2;</code>
       */
      public Builder clearStats() {
        if (statsBuilder_ == null) {
          stats_ = null;
          onChanged();
        } else {
          stats_ = null;
          statsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Stats stats = 2;</code>
       */
      public com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.Builder getStatsBuilder() {
        
        onChanged();
        return getStatsFieldBuilder().getBuilder();
      }
      /**
       * <code>.Stats stats = 2;</code>
       */
      public com.widogame.minegamedataserver.grpc.CharacterMessage.StatsOrBuilder getStatsOrBuilder() {
        if (statsBuilder_ != null) {
          return statsBuilder_.getMessageOrBuilder();
        } else {
          return stats_ == null ?
              com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.getDefaultInstance() : stats_;
        }
      }
      /**
       * <code>.Stats stats = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.widogame.minegamedataserver.grpc.CharacterMessage.Stats, com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.Builder, com.widogame.minegamedataserver.grpc.CharacterMessage.StatsOrBuilder> 
          getStatsFieldBuilder() {
        if (statsBuilder_ == null) {
          statsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.widogame.minegamedataserver.grpc.CharacterMessage.Stats, com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.Builder, com.widogame.minegamedataserver.grpc.CharacterMessage.StatsOrBuilder>(
                  getStats(),
                  getParentForChildren(),
                  isClean());
          stats_ = null;
        }
        return statsBuilder_;
      }

      private long adn_ ;
      /**
       * <code>int64 adn = 3;</code>
       * @return The adn.
       */
      @java.lang.Override
      public long getAdn() {
        return adn_;
      }
      /**
       * <code>int64 adn = 3;</code>
       * @param value The adn to set.
       * @return This builder for chaining.
       */
      public Builder setAdn(long value) {
        
        adn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 adn = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAdn() {
        
        adn_ = 0L;
        onChanged();
        return this;
      }

      private long ownerId_ ;
      /**
       * <code>int64 ownerId = 4;</code>
       * @return The ownerId.
       */
      @java.lang.Override
      public long getOwnerId() {
        return ownerId_;
      }
      /**
       * <code>int64 ownerId = 4;</code>
       * @param value The ownerId to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerId(long value) {
        
        ownerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ownerId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerId() {
        
        ownerId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InventoryCharacterResult)
    }

    // @@protoc_insertion_point(class_scope:InventoryCharacterResult)
    private static final com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult();
    }

    public static com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InventoryCharacterResult>
        PARSER = new com.google.protobuf.AbstractParser<InventoryCharacterResult>() {
      @java.lang.Override
      public InventoryCharacterResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InventoryCharacterResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InventoryCharacterResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InventoryCharacterResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.CharacterMessage.InventoryCharacterResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StatsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Stats)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float atkDamage = 1;</code>
     * @return The atkDamage.
     */
    float getAtkDamage();

    /**
     * <code>float atkSpeed = 2;</code>
     * @return The atkSpeed.
     */
    float getAtkSpeed();

    /**
     * <code>float hp = 3;</code>
     * @return The hp.
     */
    float getHp();

    /**
     * <code>float moveSpeed = 4;</code>
     * @return The moveSpeed.
     */
    float getMoveSpeed();
  }
  /**
   * Protobuf type {@code Stats}
   */
  public static final class Stats extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Stats)
      StatsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Stats.newBuilder() to construct.
    private Stats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Stats() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Stats();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Stats(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              atkDamage_ = input.readFloat();
              break;
            }
            case 21: {

              atkSpeed_ = input.readFloat();
              break;
            }
            case 29: {

              hp_ = input.readFloat();
              break;
            }
            case 37: {

              moveSpeed_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_Stats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_Stats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.class, com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.Builder.class);
    }

    public static final int ATKDAMAGE_FIELD_NUMBER = 1;
    private float atkDamage_;
    /**
     * <code>float atkDamage = 1;</code>
     * @return The atkDamage.
     */
    @java.lang.Override
    public float getAtkDamage() {
      return atkDamage_;
    }

    public static final int ATKSPEED_FIELD_NUMBER = 2;
    private float atkSpeed_;
    /**
     * <code>float atkSpeed = 2;</code>
     * @return The atkSpeed.
     */
    @java.lang.Override
    public float getAtkSpeed() {
      return atkSpeed_;
    }

    public static final int HP_FIELD_NUMBER = 3;
    private float hp_;
    /**
     * <code>float hp = 3;</code>
     * @return The hp.
     */
    @java.lang.Override
    public float getHp() {
      return hp_;
    }

    public static final int MOVESPEED_FIELD_NUMBER = 4;
    private float moveSpeed_;
    /**
     * <code>float moveSpeed = 4;</code>
     * @return The moveSpeed.
     */
    @java.lang.Override
    public float getMoveSpeed() {
      return moveSpeed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(atkDamage_) != 0) {
        output.writeFloat(1, atkDamage_);
      }
      if (java.lang.Float.floatToRawIntBits(atkSpeed_) != 0) {
        output.writeFloat(2, atkSpeed_);
      }
      if (java.lang.Float.floatToRawIntBits(hp_) != 0) {
        output.writeFloat(3, hp_);
      }
      if (java.lang.Float.floatToRawIntBits(moveSpeed_) != 0) {
        output.writeFloat(4, moveSpeed_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(atkDamage_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, atkDamage_);
      }
      if (java.lang.Float.floatToRawIntBits(atkSpeed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, atkSpeed_);
      }
      if (java.lang.Float.floatToRawIntBits(hp_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, hp_);
      }
      if (java.lang.Float.floatToRawIntBits(moveSpeed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, moveSpeed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.widogame.minegamedataserver.grpc.CharacterMessage.Stats)) {
        return super.equals(obj);
      }
      com.widogame.minegamedataserver.grpc.CharacterMessage.Stats other = (com.widogame.minegamedataserver.grpc.CharacterMessage.Stats) obj;

      if (java.lang.Float.floatToIntBits(getAtkDamage())
          != java.lang.Float.floatToIntBits(
              other.getAtkDamage())) return false;
      if (java.lang.Float.floatToIntBits(getAtkSpeed())
          != java.lang.Float.floatToIntBits(
              other.getAtkSpeed())) return false;
      if (java.lang.Float.floatToIntBits(getHp())
          != java.lang.Float.floatToIntBits(
              other.getHp())) return false;
      if (java.lang.Float.floatToIntBits(getMoveSpeed())
          != java.lang.Float.floatToIntBits(
              other.getMoveSpeed())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ATKDAMAGE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAtkDamage());
      hash = (37 * hash) + ATKSPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAtkSpeed());
      hash = (37 * hash) + HP_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHp());
      hash = (37 * hash) + MOVESPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMoveSpeed());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.widogame.minegamedataserver.grpc.CharacterMessage.Stats parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.Stats parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.Stats parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.Stats parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.Stats parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.Stats parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.Stats parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.Stats parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.Stats parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.Stats parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.Stats parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.Stats parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.widogame.minegamedataserver.grpc.CharacterMessage.Stats prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Stats}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Stats)
        com.widogame.minegamedataserver.grpc.CharacterMessage.StatsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_Stats_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_Stats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.class, com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.Builder.class);
      }

      // Construct using com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        atkDamage_ = 0F;

        atkSpeed_ = 0F;

        hp_ = 0F;

        moveSpeed_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_Stats_descriptor;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.CharacterMessage.Stats getDefaultInstanceForType() {
        return com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.getDefaultInstance();
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.CharacterMessage.Stats build() {
        com.widogame.minegamedataserver.grpc.CharacterMessage.Stats result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.CharacterMessage.Stats buildPartial() {
        com.widogame.minegamedataserver.grpc.CharacterMessage.Stats result = new com.widogame.minegamedataserver.grpc.CharacterMessage.Stats(this);
        result.atkDamage_ = atkDamage_;
        result.atkSpeed_ = atkSpeed_;
        result.hp_ = hp_;
        result.moveSpeed_ = moveSpeed_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.widogame.minegamedataserver.grpc.CharacterMessage.Stats) {
          return mergeFrom((com.widogame.minegamedataserver.grpc.CharacterMessage.Stats)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.widogame.minegamedataserver.grpc.CharacterMessage.Stats other) {
        if (other == com.widogame.minegamedataserver.grpc.CharacterMessage.Stats.getDefaultInstance()) return this;
        if (other.getAtkDamage() != 0F) {
          setAtkDamage(other.getAtkDamage());
        }
        if (other.getAtkSpeed() != 0F) {
          setAtkSpeed(other.getAtkSpeed());
        }
        if (other.getHp() != 0F) {
          setHp(other.getHp());
        }
        if (other.getMoveSpeed() != 0F) {
          setMoveSpeed(other.getMoveSpeed());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.widogame.minegamedataserver.grpc.CharacterMessage.Stats parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.widogame.minegamedataserver.grpc.CharacterMessage.Stats) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float atkDamage_ ;
      /**
       * <code>float atkDamage = 1;</code>
       * @return The atkDamage.
       */
      @java.lang.Override
      public float getAtkDamage() {
        return atkDamage_;
      }
      /**
       * <code>float atkDamage = 1;</code>
       * @param value The atkDamage to set.
       * @return This builder for chaining.
       */
      public Builder setAtkDamage(float value) {
        
        atkDamage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float atkDamage = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAtkDamage() {
        
        atkDamage_ = 0F;
        onChanged();
        return this;
      }

      private float atkSpeed_ ;
      /**
       * <code>float atkSpeed = 2;</code>
       * @return The atkSpeed.
       */
      @java.lang.Override
      public float getAtkSpeed() {
        return atkSpeed_;
      }
      /**
       * <code>float atkSpeed = 2;</code>
       * @param value The atkSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setAtkSpeed(float value) {
        
        atkSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float atkSpeed = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAtkSpeed() {
        
        atkSpeed_ = 0F;
        onChanged();
        return this;
      }

      private float hp_ ;
      /**
       * <code>float hp = 3;</code>
       * @return The hp.
       */
      @java.lang.Override
      public float getHp() {
        return hp_;
      }
      /**
       * <code>float hp = 3;</code>
       * @param value The hp to set.
       * @return This builder for chaining.
       */
      public Builder setHp(float value) {
        
        hp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float hp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHp() {
        
        hp_ = 0F;
        onChanged();
        return this;
      }

      private float moveSpeed_ ;
      /**
       * <code>float moveSpeed = 4;</code>
       * @return The moveSpeed.
       */
      @java.lang.Override
      public float getMoveSpeed() {
        return moveSpeed_;
      }
      /**
       * <code>float moveSpeed = 4;</code>
       * @param value The moveSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setMoveSpeed(float value) {
        
        moveSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float moveSpeed = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMoveSpeed() {
        
        moveSpeed_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Stats)
    }

    // @@protoc_insertion_point(class_scope:Stats)
    private static final com.widogame.minegamedataserver.grpc.CharacterMessage.Stats DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.widogame.minegamedataserver.grpc.CharacterMessage.Stats();
    }

    public static com.widogame.minegamedataserver.grpc.CharacterMessage.Stats getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Stats>
        PARSER = new com.google.protobuf.AbstractParser<Stats>() {
      @java.lang.Override
      public Stats parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Stats(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Stats> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Stats> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.CharacterMessage.Stats getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CharacterStatsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CharacterStats)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 partId = 2;</code>
     * @return The partId.
     */
    int getPartId();

    /**
     * <code>int32 partType = 3;</code>
     * @return The partType.
     */
    int getPartType();

    /**
     * <code>float atkDamage = 4;</code>
     * @return The atkDamage.
     */
    float getAtkDamage();

    /**
     * <code>float atkSpeed = 5;</code>
     * @return The atkSpeed.
     */
    float getAtkSpeed();

    /**
     * <code>float hp = 6;</code>
     * @return The hp.
     */
    float getHp();

    /**
     * <code>float moveSpeed = 7;</code>
     * @return The moveSpeed.
     */
    float getMoveSpeed();

    /**
     * <code>float stamina = 8;</code>
     * @return The stamina.
     */
    float getStamina();

    /**
     * <code>repeated int32 skillId = 9;</code>
     * @return A list containing the skillId.
     */
    java.util.List<java.lang.Integer> getSkillIdList();
    /**
     * <code>repeated int32 skillId = 9;</code>
     * @return The count of skillId.
     */
    int getSkillIdCount();
    /**
     * <code>repeated int32 skillId = 9;</code>
     * @param index The index of the element to return.
     * @return The skillId at the given index.
     */
    int getSkillId(int index);
  }
  /**
   * Protobuf type {@code CharacterStats}
   */
  public static final class CharacterStats extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CharacterStats)
      CharacterStatsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CharacterStats.newBuilder() to construct.
    private CharacterStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CharacterStats() {
      skillId_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CharacterStats();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CharacterStats(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              partId_ = input.readInt32();
              break;
            }
            case 24: {

              partType_ = input.readInt32();
              break;
            }
            case 37: {

              atkDamage_ = input.readFloat();
              break;
            }
            case 45: {

              atkSpeed_ = input.readFloat();
              break;
            }
            case 53: {

              hp_ = input.readFloat();
              break;
            }
            case 61: {

              moveSpeed_ = input.readFloat();
              break;
            }
            case 69: {

              stamina_ = input.readFloat();
              break;
            }
            case 72: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                skillId_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              skillId_.addInt(input.readInt32());
              break;
            }
            case 74: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                skillId_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                skillId_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          skillId_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_CharacterStats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_CharacterStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.class, com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int PARTID_FIELD_NUMBER = 2;
    private int partId_;
    /**
     * <code>int32 partId = 2;</code>
     * @return The partId.
     */
    @java.lang.Override
    public int getPartId() {
      return partId_;
    }

    public static final int PARTTYPE_FIELD_NUMBER = 3;
    private int partType_;
    /**
     * <code>int32 partType = 3;</code>
     * @return The partType.
     */
    @java.lang.Override
    public int getPartType() {
      return partType_;
    }

    public static final int ATKDAMAGE_FIELD_NUMBER = 4;
    private float atkDamage_;
    /**
     * <code>float atkDamage = 4;</code>
     * @return The atkDamage.
     */
    @java.lang.Override
    public float getAtkDamage() {
      return atkDamage_;
    }

    public static final int ATKSPEED_FIELD_NUMBER = 5;
    private float atkSpeed_;
    /**
     * <code>float atkSpeed = 5;</code>
     * @return The atkSpeed.
     */
    @java.lang.Override
    public float getAtkSpeed() {
      return atkSpeed_;
    }

    public static final int HP_FIELD_NUMBER = 6;
    private float hp_;
    /**
     * <code>float hp = 6;</code>
     * @return The hp.
     */
    @java.lang.Override
    public float getHp() {
      return hp_;
    }

    public static final int MOVESPEED_FIELD_NUMBER = 7;
    private float moveSpeed_;
    /**
     * <code>float moveSpeed = 7;</code>
     * @return The moveSpeed.
     */
    @java.lang.Override
    public float getMoveSpeed() {
      return moveSpeed_;
    }

    public static final int STAMINA_FIELD_NUMBER = 8;
    private float stamina_;
    /**
     * <code>float stamina = 8;</code>
     * @return The stamina.
     */
    @java.lang.Override
    public float getStamina() {
      return stamina_;
    }

    public static final int SKILLID_FIELD_NUMBER = 9;
    private com.google.protobuf.Internal.IntList skillId_;
    /**
     * <code>repeated int32 skillId = 9;</code>
     * @return A list containing the skillId.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getSkillIdList() {
      return skillId_;
    }
    /**
     * <code>repeated int32 skillId = 9;</code>
     * @return The count of skillId.
     */
    public int getSkillIdCount() {
      return skillId_.size();
    }
    /**
     * <code>repeated int32 skillId = 9;</code>
     * @param index The index of the element to return.
     * @return The skillId at the given index.
     */
    public int getSkillId(int index) {
      return skillId_.getInt(index);
    }
    private int skillIdMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (partId_ != 0) {
        output.writeInt32(2, partId_);
      }
      if (partType_ != 0) {
        output.writeInt32(3, partType_);
      }
      if (java.lang.Float.floatToRawIntBits(atkDamage_) != 0) {
        output.writeFloat(4, atkDamage_);
      }
      if (java.lang.Float.floatToRawIntBits(atkSpeed_) != 0) {
        output.writeFloat(5, atkSpeed_);
      }
      if (java.lang.Float.floatToRawIntBits(hp_) != 0) {
        output.writeFloat(6, hp_);
      }
      if (java.lang.Float.floatToRawIntBits(moveSpeed_) != 0) {
        output.writeFloat(7, moveSpeed_);
      }
      if (java.lang.Float.floatToRawIntBits(stamina_) != 0) {
        output.writeFloat(8, stamina_);
      }
      if (getSkillIdList().size() > 0) {
        output.writeUInt32NoTag(74);
        output.writeUInt32NoTag(skillIdMemoizedSerializedSize);
      }
      for (int i = 0; i < skillId_.size(); i++) {
        output.writeInt32NoTag(skillId_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (partId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, partId_);
      }
      if (partType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, partType_);
      }
      if (java.lang.Float.floatToRawIntBits(atkDamage_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, atkDamage_);
      }
      if (java.lang.Float.floatToRawIntBits(atkSpeed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, atkSpeed_);
      }
      if (java.lang.Float.floatToRawIntBits(hp_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, hp_);
      }
      if (java.lang.Float.floatToRawIntBits(moveSpeed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, moveSpeed_);
      }
      if (java.lang.Float.floatToRawIntBits(stamina_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, stamina_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < skillId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(skillId_.getInt(i));
        }
        size += dataSize;
        if (!getSkillIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        skillIdMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats)) {
        return super.equals(obj);
      }
      com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats other = (com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats) obj;

      if (getId()
          != other.getId()) return false;
      if (getPartId()
          != other.getPartId()) return false;
      if (getPartType()
          != other.getPartType()) return false;
      if (java.lang.Float.floatToIntBits(getAtkDamage())
          != java.lang.Float.floatToIntBits(
              other.getAtkDamage())) return false;
      if (java.lang.Float.floatToIntBits(getAtkSpeed())
          != java.lang.Float.floatToIntBits(
              other.getAtkSpeed())) return false;
      if (java.lang.Float.floatToIntBits(getHp())
          != java.lang.Float.floatToIntBits(
              other.getHp())) return false;
      if (java.lang.Float.floatToIntBits(getMoveSpeed())
          != java.lang.Float.floatToIntBits(
              other.getMoveSpeed())) return false;
      if (java.lang.Float.floatToIntBits(getStamina())
          != java.lang.Float.floatToIntBits(
              other.getStamina())) return false;
      if (!getSkillIdList()
          .equals(other.getSkillIdList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + PARTID_FIELD_NUMBER;
      hash = (53 * hash) + getPartId();
      hash = (37 * hash) + PARTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPartType();
      hash = (37 * hash) + ATKDAMAGE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAtkDamage());
      hash = (37 * hash) + ATKSPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAtkSpeed());
      hash = (37 * hash) + HP_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHp());
      hash = (37 * hash) + MOVESPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMoveSpeed());
      hash = (37 * hash) + STAMINA_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getStamina());
      if (getSkillIdCount() > 0) {
        hash = (37 * hash) + SKILLID_FIELD_NUMBER;
        hash = (53 * hash) + getSkillIdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CharacterStats}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CharacterStats)
        com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStatsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_CharacterStats_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_CharacterStats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.class, com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.Builder.class);
      }

      // Construct using com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        partId_ = 0;

        partType_ = 0;

        atkDamage_ = 0F;

        atkSpeed_ = 0F;

        hp_ = 0F;

        moveSpeed_ = 0F;

        stamina_ = 0F;

        skillId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.widogame.minegamedataserver.grpc.CharacterMessage.internal_static_CharacterStats_descriptor;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats getDefaultInstanceForType() {
        return com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.getDefaultInstance();
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats build() {
        com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats buildPartial() {
        com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats result = new com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.partId_ = partId_;
        result.partType_ = partType_;
        result.atkDamage_ = atkDamage_;
        result.atkSpeed_ = atkSpeed_;
        result.hp_ = hp_;
        result.moveSpeed_ = moveSpeed_;
        result.stamina_ = stamina_;
        if (((bitField0_ & 0x00000001) != 0)) {
          skillId_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.skillId_ = skillId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats) {
          return mergeFrom((com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats other) {
        if (other == com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getPartId() != 0) {
          setPartId(other.getPartId());
        }
        if (other.getPartType() != 0) {
          setPartType(other.getPartType());
        }
        if (other.getAtkDamage() != 0F) {
          setAtkDamage(other.getAtkDamage());
        }
        if (other.getAtkSpeed() != 0F) {
          setAtkSpeed(other.getAtkSpeed());
        }
        if (other.getHp() != 0F) {
          setHp(other.getHp());
        }
        if (other.getMoveSpeed() != 0F) {
          setMoveSpeed(other.getMoveSpeed());
        }
        if (other.getStamina() != 0F) {
          setStamina(other.getStamina());
        }
        if (!other.skillId_.isEmpty()) {
          if (skillId_.isEmpty()) {
            skillId_ = other.skillId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSkillIdIsMutable();
            skillId_.addAll(other.skillId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int partId_ ;
      /**
       * <code>int32 partId = 2;</code>
       * @return The partId.
       */
      @java.lang.Override
      public int getPartId() {
        return partId_;
      }
      /**
       * <code>int32 partId = 2;</code>
       * @param value The partId to set.
       * @return This builder for chaining.
       */
      public Builder setPartId(int value) {
        
        partId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 partId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartId() {
        
        partId_ = 0;
        onChanged();
        return this;
      }

      private int partType_ ;
      /**
       * <code>int32 partType = 3;</code>
       * @return The partType.
       */
      @java.lang.Override
      public int getPartType() {
        return partType_;
      }
      /**
       * <code>int32 partType = 3;</code>
       * @param value The partType to set.
       * @return This builder for chaining.
       */
      public Builder setPartType(int value) {
        
        partType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 partType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartType() {
        
        partType_ = 0;
        onChanged();
        return this;
      }

      private float atkDamage_ ;
      /**
       * <code>float atkDamage = 4;</code>
       * @return The atkDamage.
       */
      @java.lang.Override
      public float getAtkDamage() {
        return atkDamage_;
      }
      /**
       * <code>float atkDamage = 4;</code>
       * @param value The atkDamage to set.
       * @return This builder for chaining.
       */
      public Builder setAtkDamage(float value) {
        
        atkDamage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float atkDamage = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAtkDamage() {
        
        atkDamage_ = 0F;
        onChanged();
        return this;
      }

      private float atkSpeed_ ;
      /**
       * <code>float atkSpeed = 5;</code>
       * @return The atkSpeed.
       */
      @java.lang.Override
      public float getAtkSpeed() {
        return atkSpeed_;
      }
      /**
       * <code>float atkSpeed = 5;</code>
       * @param value The atkSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setAtkSpeed(float value) {
        
        atkSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float atkSpeed = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAtkSpeed() {
        
        atkSpeed_ = 0F;
        onChanged();
        return this;
      }

      private float hp_ ;
      /**
       * <code>float hp = 6;</code>
       * @return The hp.
       */
      @java.lang.Override
      public float getHp() {
        return hp_;
      }
      /**
       * <code>float hp = 6;</code>
       * @param value The hp to set.
       * @return This builder for chaining.
       */
      public Builder setHp(float value) {
        
        hp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float hp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHp() {
        
        hp_ = 0F;
        onChanged();
        return this;
      }

      private float moveSpeed_ ;
      /**
       * <code>float moveSpeed = 7;</code>
       * @return The moveSpeed.
       */
      @java.lang.Override
      public float getMoveSpeed() {
        return moveSpeed_;
      }
      /**
       * <code>float moveSpeed = 7;</code>
       * @param value The moveSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setMoveSpeed(float value) {
        
        moveSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float moveSpeed = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMoveSpeed() {
        
        moveSpeed_ = 0F;
        onChanged();
        return this;
      }

      private float stamina_ ;
      /**
       * <code>float stamina = 8;</code>
       * @return The stamina.
       */
      @java.lang.Override
      public float getStamina() {
        return stamina_;
      }
      /**
       * <code>float stamina = 8;</code>
       * @param value The stamina to set.
       * @return This builder for chaining.
       */
      public Builder setStamina(float value) {
        
        stamina_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float stamina = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearStamina() {
        
        stamina_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList skillId_ = emptyIntList();
      private void ensureSkillIdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          skillId_ = mutableCopy(skillId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 skillId = 9;</code>
       * @return A list containing the skillId.
       */
      public java.util.List<java.lang.Integer>
          getSkillIdList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(skillId_) : skillId_;
      }
      /**
       * <code>repeated int32 skillId = 9;</code>
       * @return The count of skillId.
       */
      public int getSkillIdCount() {
        return skillId_.size();
      }
      /**
       * <code>repeated int32 skillId = 9;</code>
       * @param index The index of the element to return.
       * @return The skillId at the given index.
       */
      public int getSkillId(int index) {
        return skillId_.getInt(index);
      }
      /**
       * <code>repeated int32 skillId = 9;</code>
       * @param index The index to set the value at.
       * @param value The skillId to set.
       * @return This builder for chaining.
       */
      public Builder setSkillId(
          int index, int value) {
        ensureSkillIdIsMutable();
        skillId_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 skillId = 9;</code>
       * @param value The skillId to add.
       * @return This builder for chaining.
       */
      public Builder addSkillId(int value) {
        ensureSkillIdIsMutable();
        skillId_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 skillId = 9;</code>
       * @param values The skillId to add.
       * @return This builder for chaining.
       */
      public Builder addAllSkillId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSkillIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, skillId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 skillId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSkillId() {
        skillId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CharacterStats)
    }

    // @@protoc_insertion_point(class_scope:CharacterStats)
    private static final com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats();
    }

    public static com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CharacterStats>
        PARSER = new com.google.protobuf.AbstractParser<CharacterStats>() {
      @java.lang.Override
      public CharacterStats parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CharacterStats(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CharacterStats> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CharacterStats> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InventoryCharacterResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InventoryCharacterResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Stats_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Stats_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CharacterStats_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CharacterStats_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037messages/CharacterMessage.proto\"[\n\030Inv" +
      "entoryCharacterResult\022\n\n\002id\030\001 \001(\005\022\025\n\005sta" +
      "ts\030\002 \001(\0132\006.Stats\022\013\n\003adn\030\003 \001(\003\022\017\n\007ownerId" +
      "\030\004 \001(\003\"K\n\005Stats\022\021\n\tatkDamage\030\001 \001(\002\022\020\n\010at" +
      "kSpeed\030\002 \001(\002\022\n\n\002hp\030\003 \001(\002\022\021\n\tmoveSpeed\030\004 " +
      "\001(\002\"\244\001\n\016CharacterStats\022\n\n\002id\030\001 \001(\005\022\016\n\006pa" +
      "rtId\030\002 \001(\005\022\020\n\010partType\030\003 \001(\005\022\021\n\tatkDamag" +
      "e\030\004 \001(\002\022\020\n\010atkSpeed\030\005 \001(\002\022\n\n\002hp\030\006 \001(\002\022\021\n" +
      "\tmoveSpeed\030\007 \001(\002\022\017\n\007stamina\030\010 \001(\002\022\017\n\007ski" +
      "llId\030\t \003(\005B_\n$com.widogame.minegamedatas" +
      "erver.grpcB\020CharacterMessage\252\002$com.widog" +
      "ame.minegamedataserver.grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_InventoryCharacterResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InventoryCharacterResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InventoryCharacterResult_descriptor,
        new java.lang.String[] { "Id", "Stats", "Adn", "OwnerId", });
    internal_static_Stats_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Stats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Stats_descriptor,
        new java.lang.String[] { "AtkDamage", "AtkSpeed", "Hp", "MoveSpeed", });
    internal_static_CharacterStats_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CharacterStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CharacterStats_descriptor,
        new java.lang.String[] { "Id", "PartId", "PartType", "AtkDamage", "AtkSpeed", "Hp", "MoveSpeed", "Stamina", "SkillId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
