// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/FrontendService.proto

package com.widogame.minegamedataserver.grpc;

public final class FrontendServiceOuterClass {
  private FrontendServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035service/FrontendService.proto\022\topenmat" +
      "ch\032\036messages/FrontendMessage.proto\032\034goog" +
      "le/api/annotations.proto\032.protoc-gen-ope" +
      "napiv2/options/annotations.proto\032\033google" +
      "/protobuf/empty.proto2\352\007\n\017FrontendServic" +
      "e\022U\n\014CreateTicket\022\024.CreateTicketRequest\032" +
      "\007.Ticket\"&\202\323\344\223\002 \"\033/v1/frontendservice/ti" +
      "ckets:\001*\022m\n\014DeleteTicket\022\024.DeleteTicketR" +
      "equest\032\026.google.protobuf.Empty\"/\202\323\344\223\002)*\'" +
      "/v1/frontendservice/tickets/{ticket_id}\022" +
      "X\n\tGetTicket\022\021.GetTicketRequest\032\007.Ticket" +
      "\"/\202\323\344\223\002)\022\'/v1/frontendservice/tickets/{t" +
      "icket_id}\022\206\001\n\020WatchAssignments\022\030.WatchAs" +
      "signmentsRequest\032\031.WatchAssignmentsRespo" +
      "nse\";\202\323\344\223\0025\0223/v1/frontendservice/tickets" +
      "/{ticket_id}/assignments0\001\022\224\001\n\023Acknowled" +
      "geBackfill\022\033.AcknowledgeBackfillRequest\032" +
      "\034.AcknowledgeBackfillResponse\"B\202\323\344\223\002<\"7/" +
      "v1/frontendservice/backfills/{backfill_i" +
      "d}/acknowledge:\001*\022]\n\016CreateBackfill\022\026.Cr" +
      "eateBackfillRequest\032\t.Backfill\"(\202\323\344\223\002\"\"\035" +
      "/v1/frontendservice/backfills:\001*\022u\n\016Dele" +
      "teBackfill\022\026.DeleteBackfillRequest\032\026.goo" +
      "gle.protobuf.Empty\"3\202\323\344\223\002-*+/v1/frontend" +
      "service/backfills/{backfill_id}\022b\n\013GetBa" +
      "ckfill\022\023.GetBackfillRequest\032\t.Backfill\"3" +
      "\202\323\344\223\002-\022+/v1/frontendservice/backfills/{b" +
      "ackfill_id}\022]\n\016UpdateBackfill\022\026.UpdateBa" +
      "ckfillRequest\032\t.Backfill\"(\202\323\344\223\002\"2\035/v1/fr" +
      "ontendservice/backfills:\001*B\314\003\n$com.widog" +
      "ame.minegamedataserver.grpcZ open-match." +
      "dev/open-match/pkg/pb\252\002$com.widogame.min" +
      "egamedataserver.grpc\222A\331\002\022\262\001\n\010Frontend\"I\n" +
      "\nOpen Match\022\026https://open-match.dev\032#ope" +
      "n-match-discuss@googlegroups.com*V\n\022Apac" +
      "he 2.0 License\022@https://github.com/googl" +
      "eforgames/open-match/blob/master/LICENSE" +
      "2\0031.0*\002\001\0022\020application/json:\020application" +
      "/jsonR;\n\003404\0224\n*Returned when the resour" +
      "ce does not exist.\022\006\n\004\232\002\001\007r=\n\030Open Match" +
      " Documentation\022!https://open-match.dev/s" +
      "ite/docs/b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.widogame.minegamedataserver.grpc.FrontendMessage.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          grpc.gateway.protoc_gen_openapiv2.options.Annotations.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(grpc.gateway.protoc_gen_openapiv2.options.Annotations.openapiv2Swagger);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.widogame.minegamedataserver.grpc.FrontendMessage.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    grpc.gateway.protoc_gen_openapiv2.options.Annotations.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
