// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/GameCommonService.proto

package com.widogame.minegamedataserver.grpc;

public final class GameCommonService {
  private GameCommonService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameConfigurationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameConfigurationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>repeated .CharacterStats characterStats = 2;</code>
     */
    java.util.List<com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats> 
        getCharacterStatsList();
    /**
     * <code>repeated .CharacterStats characterStats = 2;</code>
     */
    com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats getCharacterStats(int index);
    /**
     * <code>repeated .CharacterStats characterStats = 2;</code>
     */
    int getCharacterStatsCount();
    /**
     * <code>repeated .CharacterStats characterStats = 2;</code>
     */
    java.util.List<? extends com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStatsOrBuilder> 
        getCharacterStatsOrBuilderList();
    /**
     * <code>repeated .CharacterStats characterStats = 2;</code>
     */
    com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStatsOrBuilder getCharacterStatsOrBuilder(
        int index);

    /**
     * <code>repeated .Skills skills = 3;</code>
     */
    java.util.List<com.widogame.minegamedataserver.grpc.SkillsMessage.Skills> 
        getSkillsList();
    /**
     * <code>repeated .Skills skills = 3;</code>
     */
    com.widogame.minegamedataserver.grpc.SkillsMessage.Skills getSkills(int index);
    /**
     * <code>repeated .Skills skills = 3;</code>
     */
    int getSkillsCount();
    /**
     * <code>repeated .Skills skills = 3;</code>
     */
    java.util.List<? extends com.widogame.minegamedataserver.grpc.SkillsMessage.SkillsOrBuilder> 
        getSkillsOrBuilderList();
    /**
     * <code>repeated .Skills skills = 3;</code>
     */
    com.widogame.minegamedataserver.grpc.SkillsMessage.SkillsOrBuilder getSkillsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GameConfigurationResponse}
   */
  public static final class GameConfigurationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GameConfigurationResponse)
      GameConfigurationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameConfigurationResponse.newBuilder() to construct.
    private GameConfigurationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameConfigurationResponse() {
      characterStats_ = java.util.Collections.emptyList();
      skills_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameConfigurationResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameConfigurationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                characterStats_ = new java.util.ArrayList<com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats>();
                mutable_bitField0_ |= 0x00000001;
              }
              characterStats_.add(
                  input.readMessage(com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.parser(), extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                skills_ = new java.util.ArrayList<com.widogame.minegamedataserver.grpc.SkillsMessage.Skills>();
                mutable_bitField0_ |= 0x00000002;
              }
              skills_.add(
                  input.readMessage(com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          characterStats_ = java.util.Collections.unmodifiableList(characterStats_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          skills_ = java.util.Collections.unmodifiableList(skills_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.widogame.minegamedataserver.grpc.GameCommonService.internal_static_GameConfigurationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.widogame.minegamedataserver.grpc.GameCommonService.internal_static_GameConfigurationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse.class, com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int CHARACTERSTATS_FIELD_NUMBER = 2;
    private java.util.List<com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats> characterStats_;
    /**
     * <code>repeated .CharacterStats characterStats = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats> getCharacterStatsList() {
      return characterStats_;
    }
    /**
     * <code>repeated .CharacterStats characterStats = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStatsOrBuilder> 
        getCharacterStatsOrBuilderList() {
      return characterStats_;
    }
    /**
     * <code>repeated .CharacterStats characterStats = 2;</code>
     */
    @java.lang.Override
    public int getCharacterStatsCount() {
      return characterStats_.size();
    }
    /**
     * <code>repeated .CharacterStats characterStats = 2;</code>
     */
    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats getCharacterStats(int index) {
      return characterStats_.get(index);
    }
    /**
     * <code>repeated .CharacterStats characterStats = 2;</code>
     */
    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStatsOrBuilder getCharacterStatsOrBuilder(
        int index) {
      return characterStats_.get(index);
    }

    public static final int SKILLS_FIELD_NUMBER = 3;
    private java.util.List<com.widogame.minegamedataserver.grpc.SkillsMessage.Skills> skills_;
    /**
     * <code>repeated .Skills skills = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.widogame.minegamedataserver.grpc.SkillsMessage.Skills> getSkillsList() {
      return skills_;
    }
    /**
     * <code>repeated .Skills skills = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.widogame.minegamedataserver.grpc.SkillsMessage.SkillsOrBuilder> 
        getSkillsOrBuilderList() {
      return skills_;
    }
    /**
     * <code>repeated .Skills skills = 3;</code>
     */
    @java.lang.Override
    public int getSkillsCount() {
      return skills_.size();
    }
    /**
     * <code>repeated .Skills skills = 3;</code>
     */
    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.SkillsMessage.Skills getSkills(int index) {
      return skills_.get(index);
    }
    /**
     * <code>repeated .Skills skills = 3;</code>
     */
    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.SkillsMessage.SkillsOrBuilder getSkillsOrBuilder(
        int index) {
      return skills_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeInt32(1, version_);
      }
      for (int i = 0; i < characterStats_.size(); i++) {
        output.writeMessage(2, characterStats_.get(i));
      }
      for (int i = 0; i < skills_.size(); i++) {
        output.writeMessage(3, skills_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      for (int i = 0; i < characterStats_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, characterStats_.get(i));
      }
      for (int i = 0; i < skills_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, skills_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse)) {
        return super.equals(obj);
      }
      com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse other = (com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (!getCharacterStatsList()
          .equals(other.getCharacterStatsList())) return false;
      if (!getSkillsList()
          .equals(other.getSkillsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      if (getCharacterStatsCount() > 0) {
        hash = (37 * hash) + CHARACTERSTATS_FIELD_NUMBER;
        hash = (53 * hash) + getCharacterStatsList().hashCode();
      }
      if (getSkillsCount() > 0) {
        hash = (37 * hash) + SKILLS_FIELD_NUMBER;
        hash = (53 * hash) + getSkillsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GameConfigurationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameConfigurationResponse)
        com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.widogame.minegamedataserver.grpc.GameCommonService.internal_static_GameConfigurationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.widogame.minegamedataserver.grpc.GameCommonService.internal_static_GameConfigurationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse.class, com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse.Builder.class);
      }

      // Construct using com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCharacterStatsFieldBuilder();
          getSkillsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        if (characterStatsBuilder_ == null) {
          characterStats_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          characterStatsBuilder_.clear();
        }
        if (skillsBuilder_ == null) {
          skills_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          skillsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.widogame.minegamedataserver.grpc.GameCommonService.internal_static_GameConfigurationResponse_descriptor;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse getDefaultInstanceForType() {
        return com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse build() {
        com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse buildPartial() {
        com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse result = new com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse(this);
        int from_bitField0_ = bitField0_;
        result.version_ = version_;
        if (characterStatsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            characterStats_ = java.util.Collections.unmodifiableList(characterStats_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.characterStats_ = characterStats_;
        } else {
          result.characterStats_ = characterStatsBuilder_.build();
        }
        if (skillsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            skills_ = java.util.Collections.unmodifiableList(skills_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.skills_ = skills_;
        } else {
          result.skills_ = skillsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse) {
          return mergeFrom((com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse other) {
        if (other == com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (characterStatsBuilder_ == null) {
          if (!other.characterStats_.isEmpty()) {
            if (characterStats_.isEmpty()) {
              characterStats_ = other.characterStats_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCharacterStatsIsMutable();
              characterStats_.addAll(other.characterStats_);
            }
            onChanged();
          }
        } else {
          if (!other.characterStats_.isEmpty()) {
            if (characterStatsBuilder_.isEmpty()) {
              characterStatsBuilder_.dispose();
              characterStatsBuilder_ = null;
              characterStats_ = other.characterStats_;
              bitField0_ = (bitField0_ & ~0x00000001);
              characterStatsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCharacterStatsFieldBuilder() : null;
            } else {
              characterStatsBuilder_.addAllMessages(other.characterStats_);
            }
          }
        }
        if (skillsBuilder_ == null) {
          if (!other.skills_.isEmpty()) {
            if (skills_.isEmpty()) {
              skills_ = other.skills_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSkillsIsMutable();
              skills_.addAll(other.skills_);
            }
            onChanged();
          }
        } else {
          if (!other.skills_.isEmpty()) {
            if (skillsBuilder_.isEmpty()) {
              skillsBuilder_.dispose();
              skillsBuilder_ = null;
              skills_ = other.skills_;
              bitField0_ = (bitField0_ & ~0x00000002);
              skillsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSkillsFieldBuilder() : null;
            } else {
              skillsBuilder_.addAllMessages(other.skills_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>int32 version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats> characterStats_ =
        java.util.Collections.emptyList();
      private void ensureCharacterStatsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          characterStats_ = new java.util.ArrayList<com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats>(characterStats_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats, com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.Builder, com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStatsOrBuilder> characterStatsBuilder_;

      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public java.util.List<com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats> getCharacterStatsList() {
        if (characterStatsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(characterStats_);
        } else {
          return characterStatsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public int getCharacterStatsCount() {
        if (characterStatsBuilder_ == null) {
          return characterStats_.size();
        } else {
          return characterStatsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats getCharacterStats(int index) {
        if (characterStatsBuilder_ == null) {
          return characterStats_.get(index);
        } else {
          return characterStatsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public Builder setCharacterStats(
          int index, com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats value) {
        if (characterStatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCharacterStatsIsMutable();
          characterStats_.set(index, value);
          onChanged();
        } else {
          characterStatsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public Builder setCharacterStats(
          int index, com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.Builder builderForValue) {
        if (characterStatsBuilder_ == null) {
          ensureCharacterStatsIsMutable();
          characterStats_.set(index, builderForValue.build());
          onChanged();
        } else {
          characterStatsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public Builder addCharacterStats(com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats value) {
        if (characterStatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCharacterStatsIsMutable();
          characterStats_.add(value);
          onChanged();
        } else {
          characterStatsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public Builder addCharacterStats(
          int index, com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats value) {
        if (characterStatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCharacterStatsIsMutable();
          characterStats_.add(index, value);
          onChanged();
        } else {
          characterStatsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public Builder addCharacterStats(
          com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.Builder builderForValue) {
        if (characterStatsBuilder_ == null) {
          ensureCharacterStatsIsMutable();
          characterStats_.add(builderForValue.build());
          onChanged();
        } else {
          characterStatsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public Builder addCharacterStats(
          int index, com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.Builder builderForValue) {
        if (characterStatsBuilder_ == null) {
          ensureCharacterStatsIsMutable();
          characterStats_.add(index, builderForValue.build());
          onChanged();
        } else {
          characterStatsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public Builder addAllCharacterStats(
          java.lang.Iterable<? extends com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats> values) {
        if (characterStatsBuilder_ == null) {
          ensureCharacterStatsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, characterStats_);
          onChanged();
        } else {
          characterStatsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public Builder clearCharacterStats() {
        if (characterStatsBuilder_ == null) {
          characterStats_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          characterStatsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public Builder removeCharacterStats(int index) {
        if (characterStatsBuilder_ == null) {
          ensureCharacterStatsIsMutable();
          characterStats_.remove(index);
          onChanged();
        } else {
          characterStatsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.Builder getCharacterStatsBuilder(
          int index) {
        return getCharacterStatsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStatsOrBuilder getCharacterStatsOrBuilder(
          int index) {
        if (characterStatsBuilder_ == null) {
          return characterStats_.get(index);  } else {
          return characterStatsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public java.util.List<? extends com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStatsOrBuilder> 
           getCharacterStatsOrBuilderList() {
        if (characterStatsBuilder_ != null) {
          return characterStatsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(characterStats_);
        }
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.Builder addCharacterStatsBuilder() {
        return getCharacterStatsFieldBuilder().addBuilder(
            com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.getDefaultInstance());
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.Builder addCharacterStatsBuilder(
          int index) {
        return getCharacterStatsFieldBuilder().addBuilder(
            index, com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.getDefaultInstance());
      }
      /**
       * <code>repeated .CharacterStats characterStats = 2;</code>
       */
      public java.util.List<com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.Builder> 
           getCharacterStatsBuilderList() {
        return getCharacterStatsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats, com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.Builder, com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStatsOrBuilder> 
          getCharacterStatsFieldBuilder() {
        if (characterStatsBuilder_ == null) {
          characterStatsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats, com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStats.Builder, com.widogame.minegamedataserver.grpc.CharacterMessage.CharacterStatsOrBuilder>(
                  characterStats_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          characterStats_ = null;
        }
        return characterStatsBuilder_;
      }

      private java.util.List<com.widogame.minegamedataserver.grpc.SkillsMessage.Skills> skills_ =
        java.util.Collections.emptyList();
      private void ensureSkillsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          skills_ = new java.util.ArrayList<com.widogame.minegamedataserver.grpc.SkillsMessage.Skills>(skills_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.widogame.minegamedataserver.grpc.SkillsMessage.Skills, com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.Builder, com.widogame.minegamedataserver.grpc.SkillsMessage.SkillsOrBuilder> skillsBuilder_;

      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public java.util.List<com.widogame.minegamedataserver.grpc.SkillsMessage.Skills> getSkillsList() {
        if (skillsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(skills_);
        } else {
          return skillsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public int getSkillsCount() {
        if (skillsBuilder_ == null) {
          return skills_.size();
        } else {
          return skillsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Skills getSkills(int index) {
        if (skillsBuilder_ == null) {
          return skills_.get(index);
        } else {
          return skillsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public Builder setSkills(
          int index, com.widogame.minegamedataserver.grpc.SkillsMessage.Skills value) {
        if (skillsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSkillsIsMutable();
          skills_.set(index, value);
          onChanged();
        } else {
          skillsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public Builder setSkills(
          int index, com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.Builder builderForValue) {
        if (skillsBuilder_ == null) {
          ensureSkillsIsMutable();
          skills_.set(index, builderForValue.build());
          onChanged();
        } else {
          skillsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public Builder addSkills(com.widogame.minegamedataserver.grpc.SkillsMessage.Skills value) {
        if (skillsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSkillsIsMutable();
          skills_.add(value);
          onChanged();
        } else {
          skillsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public Builder addSkills(
          int index, com.widogame.minegamedataserver.grpc.SkillsMessage.Skills value) {
        if (skillsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSkillsIsMutable();
          skills_.add(index, value);
          onChanged();
        } else {
          skillsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public Builder addSkills(
          com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.Builder builderForValue) {
        if (skillsBuilder_ == null) {
          ensureSkillsIsMutable();
          skills_.add(builderForValue.build());
          onChanged();
        } else {
          skillsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public Builder addSkills(
          int index, com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.Builder builderForValue) {
        if (skillsBuilder_ == null) {
          ensureSkillsIsMutable();
          skills_.add(index, builderForValue.build());
          onChanged();
        } else {
          skillsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public Builder addAllSkills(
          java.lang.Iterable<? extends com.widogame.minegamedataserver.grpc.SkillsMessage.Skills> values) {
        if (skillsBuilder_ == null) {
          ensureSkillsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, skills_);
          onChanged();
        } else {
          skillsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public Builder clearSkills() {
        if (skillsBuilder_ == null) {
          skills_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          skillsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public Builder removeSkills(int index) {
        if (skillsBuilder_ == null) {
          ensureSkillsIsMutable();
          skills_.remove(index);
          onChanged();
        } else {
          skillsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.Builder getSkillsBuilder(
          int index) {
        return getSkillsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public com.widogame.minegamedataserver.grpc.SkillsMessage.SkillsOrBuilder getSkillsOrBuilder(
          int index) {
        if (skillsBuilder_ == null) {
          return skills_.get(index);  } else {
          return skillsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public java.util.List<? extends com.widogame.minegamedataserver.grpc.SkillsMessage.SkillsOrBuilder> 
           getSkillsOrBuilderList() {
        if (skillsBuilder_ != null) {
          return skillsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(skills_);
        }
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.Builder addSkillsBuilder() {
        return getSkillsFieldBuilder().addBuilder(
            com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.getDefaultInstance());
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.Builder addSkillsBuilder(
          int index) {
        return getSkillsFieldBuilder().addBuilder(
            index, com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.getDefaultInstance());
      }
      /**
       * <code>repeated .Skills skills = 3;</code>
       */
      public java.util.List<com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.Builder> 
           getSkillsBuilderList() {
        return getSkillsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.widogame.minegamedataserver.grpc.SkillsMessage.Skills, com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.Builder, com.widogame.minegamedataserver.grpc.SkillsMessage.SkillsOrBuilder> 
          getSkillsFieldBuilder() {
        if (skillsBuilder_ == null) {
          skillsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.widogame.minegamedataserver.grpc.SkillsMessage.Skills, com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.Builder, com.widogame.minegamedataserver.grpc.SkillsMessage.SkillsOrBuilder>(
                  skills_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          skills_ = null;
        }
        return skillsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GameConfigurationResponse)
    }

    // @@protoc_insertion_point(class_scope:GameConfigurationResponse)
    private static final com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse();
    }

    public static com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameConfigurationResponse>
        PARSER = new com.google.protobuf.AbstractParser<GameConfigurationResponse>() {
      @java.lang.Override
      public GameConfigurationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameConfigurationResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameConfigurationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameConfigurationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.GameCommonService.GameConfigurationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameConfigurationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GameConfigurationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037service/GameCommonService.proto\032\037messa" +
      "ges/CharacterMessage.proto\032\034messages/Ski" +
      "llsMessage.proto\032\033google/protobuf/empty." +
      "proto\"n\n\031GameConfigurationResponse\022\017\n\007ve" +
      "rsion\030\001 \001(\005\022\'\n\016characterStats\030\002 \003(\0132\017.Ch" +
      "aracterStats\022\027\n\006skills\030\003 \003(\0132\007.Skills2Y\n" +
      "\013GameService\022J\n\024getGameConfiguration\022\026.g" +
      "oogle.protobuf.Empty\032\032.GameConfiguration" +
      "ResponseBM\n$com.widogame.minegamedataser" +
      "ver.grpc\252\002$com.widogame.minegamedataserv" +
      "er.grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.widogame.minegamedataserver.grpc.CharacterMessage.getDescriptor(),
          com.widogame.minegamedataserver.grpc.SkillsMessage.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_GameConfigurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GameConfigurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GameConfigurationResponse_descriptor,
        new java.lang.String[] { "Version", "CharacterStats", "Skills", });
    com.widogame.minegamedataserver.grpc.CharacterMessage.getDescriptor();
    com.widogame.minegamedataserver.grpc.SkillsMessage.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
