// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/PvEService.proto

package com.widogame.minegamedataserver.grpc;

public final class PvEServiceOuterClass {
  private PvEServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PvEResponesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AlloService.PvERespones)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string connTcp = 1;</code>
     * @return The connTcp.
     */
    java.lang.String getConnTcp();
    /**
     * <code>string connTcp = 1;</code>
     * @return The bytes for connTcp.
     */
    com.google.protobuf.ByteString
        getConnTcpBytes();

    /**
     * <code>string connUdp = 2;</code>
     * @return The connUdp.
     */
    java.lang.String getConnUdp();
    /**
     * <code>string connUdp = 2;</code>
     * @return The bytes for connUdp.
     */
    com.google.protobuf.ByteString
        getConnUdpBytes();
  }
  /**
   * Protobuf type {@code AlloService.PvERespones}
   */
  public static final class PvERespones extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AlloService.PvERespones)
      PvEResponesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PvERespones.newBuilder() to construct.
    private PvERespones(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PvERespones() {
      connTcp_ = "";
      connUdp_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PvERespones();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PvERespones(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              connTcp_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              connUdp_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.internal_static_AlloService_PvERespones_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.internal_static_AlloService_PvERespones_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones.class, com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones.Builder.class);
    }

    public static final int CONNTCP_FIELD_NUMBER = 1;
    private volatile java.lang.Object connTcp_;
    /**
     * <code>string connTcp = 1;</code>
     * @return The connTcp.
     */
    @java.lang.Override
    public java.lang.String getConnTcp() {
      java.lang.Object ref = connTcp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connTcp_ = s;
        return s;
      }
    }
    /**
     * <code>string connTcp = 1;</code>
     * @return The bytes for connTcp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConnTcpBytes() {
      java.lang.Object ref = connTcp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connTcp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONNUDP_FIELD_NUMBER = 2;
    private volatile java.lang.Object connUdp_;
    /**
     * <code>string connUdp = 2;</code>
     * @return The connUdp.
     */
    @java.lang.Override
    public java.lang.String getConnUdp() {
      java.lang.Object ref = connUdp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connUdp_ = s;
        return s;
      }
    }
    /**
     * <code>string connUdp = 2;</code>
     * @return The bytes for connUdp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConnUdpBytes() {
      java.lang.Object ref = connUdp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connUdp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connTcp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, connTcp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connUdp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, connUdp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connTcp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, connTcp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connUdp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, connUdp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones)) {
        return super.equals(obj);
      }
      com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones other = (com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones) obj;

      if (!getConnTcp()
          .equals(other.getConnTcp())) return false;
      if (!getConnUdp()
          .equals(other.getConnUdp())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONNTCP_FIELD_NUMBER;
      hash = (53 * hash) + getConnTcp().hashCode();
      hash = (37 * hash) + CONNUDP_FIELD_NUMBER;
      hash = (53 * hash) + getConnUdp().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AlloService.PvERespones}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AlloService.PvERespones)
        com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvEResponesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.internal_static_AlloService_PvERespones_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.internal_static_AlloService_PvERespones_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones.class, com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones.Builder.class);
      }

      // Construct using com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        connTcp_ = "";

        connUdp_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.internal_static_AlloService_PvERespones_descriptor;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones getDefaultInstanceForType() {
        return com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones.getDefaultInstance();
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones build() {
        com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones buildPartial() {
        com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones result = new com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones(this);
        result.connTcp_ = connTcp_;
        result.connUdp_ = connUdp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones) {
          return mergeFrom((com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones other) {
        if (other == com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones.getDefaultInstance()) return this;
        if (!other.getConnTcp().isEmpty()) {
          connTcp_ = other.connTcp_;
          onChanged();
        }
        if (!other.getConnUdp().isEmpty()) {
          connUdp_ = other.connUdp_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object connTcp_ = "";
      /**
       * <code>string connTcp = 1;</code>
       * @return The connTcp.
       */
      public java.lang.String getConnTcp() {
        java.lang.Object ref = connTcp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          connTcp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string connTcp = 1;</code>
       * @return The bytes for connTcp.
       */
      public com.google.protobuf.ByteString
          getConnTcpBytes() {
        java.lang.Object ref = connTcp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          connTcp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string connTcp = 1;</code>
       * @param value The connTcp to set.
       * @return This builder for chaining.
       */
      public Builder setConnTcp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        connTcp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string connTcp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnTcp() {
        
        connTcp_ = getDefaultInstance().getConnTcp();
        onChanged();
        return this;
      }
      /**
       * <code>string connTcp = 1;</code>
       * @param value The bytes for connTcp to set.
       * @return This builder for chaining.
       */
      public Builder setConnTcpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        connTcp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object connUdp_ = "";
      /**
       * <code>string connUdp = 2;</code>
       * @return The connUdp.
       */
      public java.lang.String getConnUdp() {
        java.lang.Object ref = connUdp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          connUdp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string connUdp = 2;</code>
       * @return The bytes for connUdp.
       */
      public com.google.protobuf.ByteString
          getConnUdpBytes() {
        java.lang.Object ref = connUdp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          connUdp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string connUdp = 2;</code>
       * @param value The connUdp to set.
       * @return This builder for chaining.
       */
      public Builder setConnUdp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        connUdp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string connUdp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnUdp() {
        
        connUdp_ = getDefaultInstance().getConnUdp();
        onChanged();
        return this;
      }
      /**
       * <code>string connUdp = 2;</code>
       * @param value The bytes for connUdp to set.
       * @return This builder for chaining.
       */
      public Builder setConnUdpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        connUdp_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AlloService.PvERespones)
    }

    // @@protoc_insertion_point(class_scope:AlloService.PvERespones)
    private static final com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones();
    }

    public static com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PvERespones>
        PARSER = new com.google.protobuf.AbstractParser<PvERespones>() {
      @java.lang.Override
      public PvERespones parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PvERespones(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PvERespones> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PvERespones> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.PvEServiceOuterClass.PvERespones getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AlloService_PvERespones_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AlloService_PvERespones_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030service/PvEService.proto\022\013AlloService\032" +
      "\033google/protobuf/empty.proto\"/\n\013PvERespo" +
      "nes\022\017\n\007connTcp\030\001 \001(\t\022\017\n\007connUdp\030\002 \001(\t2L\n" +
      "\nPvEService\022>\n\010startPvE\022\026.google.protobu" +
      "f.Empty\032\030.AlloService.PvERespones\"\000BW\n$c" +
      "om.widogame.minegamedataserver.grpcZ\010./a" +
      "llopb\252\002$com.widogame.minegamedataserver." +
      "grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_AlloService_PvERespones_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AlloService_PvERespones_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AlloService_PvERespones_descriptor,
        new java.lang.String[] { "ConnTcp", "ConnUdp", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
