// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/SeasonMessage.proto

package com.widogame.minegamedataserver.grpc;

public final class SeasonMessage {
  private SeasonMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LuckyBallOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LuckyBall)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 luckyNumber = 1;</code>
     * @return The luckyNumber.
     */
    int getLuckyNumber();

    /**
     * <code>float rewardMare = 2;</code>
     * @return The rewardMare.
     */
    float getRewardMare();
  }
  /**
   * Protobuf type {@code LuckyBall}
   */
  public static final class LuckyBall extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LuckyBall)
      LuckyBallOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LuckyBall.newBuilder() to construct.
    private LuckyBall(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LuckyBall() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LuckyBall();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LuckyBall(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              luckyNumber_ = input.readInt32();
              break;
            }
            case 21: {

              rewardMare_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.widogame.minegamedataserver.grpc.SeasonMessage.internal_static_LuckyBall_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.widogame.minegamedataserver.grpc.SeasonMessage.internal_static_LuckyBall_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall.class, com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall.Builder.class);
    }

    public static final int LUCKYNUMBER_FIELD_NUMBER = 1;
    private int luckyNumber_;
    /**
     * <code>int32 luckyNumber = 1;</code>
     * @return The luckyNumber.
     */
    @java.lang.Override
    public int getLuckyNumber() {
      return luckyNumber_;
    }

    public static final int REWARDMARE_FIELD_NUMBER = 2;
    private float rewardMare_;
    /**
     * <code>float rewardMare = 2;</code>
     * @return The rewardMare.
     */
    @java.lang.Override
    public float getRewardMare() {
      return rewardMare_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (luckyNumber_ != 0) {
        output.writeInt32(1, luckyNumber_);
      }
      if (java.lang.Float.floatToRawIntBits(rewardMare_) != 0) {
        output.writeFloat(2, rewardMare_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (luckyNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, luckyNumber_);
      }
      if (java.lang.Float.floatToRawIntBits(rewardMare_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, rewardMare_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall)) {
        return super.equals(obj);
      }
      com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall other = (com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall) obj;

      if (getLuckyNumber()
          != other.getLuckyNumber()) return false;
      if (java.lang.Float.floatToIntBits(getRewardMare())
          != java.lang.Float.floatToIntBits(
              other.getRewardMare())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LUCKYNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getLuckyNumber();
      hash = (37 * hash) + REWARDMARE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getRewardMare());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LuckyBall}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LuckyBall)
        com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBallOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.widogame.minegamedataserver.grpc.SeasonMessage.internal_static_LuckyBall_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.widogame.minegamedataserver.grpc.SeasonMessage.internal_static_LuckyBall_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall.class, com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall.Builder.class);
      }

      // Construct using com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        luckyNumber_ = 0;

        rewardMare_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.widogame.minegamedataserver.grpc.SeasonMessage.internal_static_LuckyBall_descriptor;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall getDefaultInstanceForType() {
        return com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall.getDefaultInstance();
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall build() {
        com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall buildPartial() {
        com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall result = new com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall(this);
        result.luckyNumber_ = luckyNumber_;
        result.rewardMare_ = rewardMare_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall) {
          return mergeFrom((com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall other) {
        if (other == com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall.getDefaultInstance()) return this;
        if (other.getLuckyNumber() != 0) {
          setLuckyNumber(other.getLuckyNumber());
        }
        if (other.getRewardMare() != 0F) {
          setRewardMare(other.getRewardMare());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int luckyNumber_ ;
      /**
       * <code>int32 luckyNumber = 1;</code>
       * @return The luckyNumber.
       */
      @java.lang.Override
      public int getLuckyNumber() {
        return luckyNumber_;
      }
      /**
       * <code>int32 luckyNumber = 1;</code>
       * @param value The luckyNumber to set.
       * @return This builder for chaining.
       */
      public Builder setLuckyNumber(int value) {
        
        luckyNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 luckyNumber = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLuckyNumber() {
        
        luckyNumber_ = 0;
        onChanged();
        return this;
      }

      private float rewardMare_ ;
      /**
       * <code>float rewardMare = 2;</code>
       * @return The rewardMare.
       */
      @java.lang.Override
      public float getRewardMare() {
        return rewardMare_;
      }
      /**
       * <code>float rewardMare = 2;</code>
       * @param value The rewardMare to set.
       * @return This builder for chaining.
       */
      public Builder setRewardMare(float value) {
        
        rewardMare_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float rewardMare = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRewardMare() {
        
        rewardMare_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LuckyBall)
    }

    // @@protoc_insertion_point(class_scope:LuckyBall)
    private static final com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall();
    }

    public static com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LuckyBall>
        PARSER = new com.google.protobuf.AbstractParser<LuckyBall>() {
      @java.lang.Override
      public LuckyBall parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LuckyBall(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LuckyBall> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LuckyBall> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.SeasonMessage.LuckyBall getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LuckyBall_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LuckyBall_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034messages/SeasonMessage.proto\"4\n\tLuckyB" +
      "all\022\023\n\013luckyNumber\030\001 \001(\005\022\022\n\nrewardMare\030\002" +
      " \001(\002BM\n$com.widogame.minegamedataserver." +
      "grpc\252\002$com.widogame.minegamedataserver.g" +
      "rpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LuckyBall_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LuckyBall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LuckyBall_descriptor,
        new java.lang.String[] { "LuckyNumber", "RewardMare", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
