// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/SkillsMessage.proto

package com.widogame.minegamedataserver.grpc;

public final class SkillsMessage {
  private SkillsMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SkillsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Skills)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 partId = 2;</code>
     * @return The partId.
     */
    int getPartId();

    /**
     * <code>int32 partType = 3;</code>
     * @return The partType.
     */
    int getPartType();

    /**
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>string name = 5;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 5;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>float animDuration = 6;</code>
     * @return The animDuration.
     */
    float getAnimDuration();

    /**
     * <code>int32 unlockLevel = 7;</code>
     * @return The unlockLevel.
     */
    int getUnlockLevel();

    /**
     * <code>repeated .Level levels = 8;</code>
     */
    java.util.List<com.widogame.minegamedataserver.grpc.SkillsMessage.Level> 
        getLevelsList();
    /**
     * <code>repeated .Level levels = 8;</code>
     */
    com.widogame.minegamedataserver.grpc.SkillsMessage.Level getLevels(int index);
    /**
     * <code>repeated .Level levels = 8;</code>
     */
    int getLevelsCount();
    /**
     * <code>repeated .Level levels = 8;</code>
     */
    java.util.List<? extends com.widogame.minegamedataserver.grpc.SkillsMessage.LevelOrBuilder> 
        getLevelsOrBuilderList();
    /**
     * <code>repeated .Level levels = 8;</code>
     */
    com.widogame.minegamedataserver.grpc.SkillsMessage.LevelOrBuilder getLevelsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Skills}
   */
  public static final class Skills extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Skills)
      SkillsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Skills.newBuilder() to construct.
    private Skills(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Skills() {
      name_ = "";
      levels_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Skills();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Skills(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              partId_ = input.readInt32();
              break;
            }
            case 24: {

              partType_ = input.readInt32();
              break;
            }
            case 32: {

              type_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 53: {

              animDuration_ = input.readFloat();
              break;
            }
            case 56: {

              unlockLevel_ = input.readInt32();
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                levels_ = new java.util.ArrayList<com.widogame.minegamedataserver.grpc.SkillsMessage.Level>();
                mutable_bitField0_ |= 0x00000001;
              }
              levels_.add(
                  input.readMessage(com.widogame.minegamedataserver.grpc.SkillsMessage.Level.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          levels_ = java.util.Collections.unmodifiableList(levels_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.widogame.minegamedataserver.grpc.SkillsMessage.internal_static_Skills_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.widogame.minegamedataserver.grpc.SkillsMessage.internal_static_Skills_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.class, com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int PARTID_FIELD_NUMBER = 2;
    private int partId_;
    /**
     * <code>int32 partId = 2;</code>
     * @return The partId.
     */
    @java.lang.Override
    public int getPartId() {
      return partId_;
    }

    public static final int PARTTYPE_FIELD_NUMBER = 3;
    private int partType_;
    /**
     * <code>int32 partType = 3;</code>
     * @return The partType.
     */
    @java.lang.Override
    public int getPartType() {
      return partType_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int NAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 5;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 5;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANIMDURATION_FIELD_NUMBER = 6;
    private float animDuration_;
    /**
     * <code>float animDuration = 6;</code>
     * @return The animDuration.
     */
    @java.lang.Override
    public float getAnimDuration() {
      return animDuration_;
    }

    public static final int UNLOCKLEVEL_FIELD_NUMBER = 7;
    private int unlockLevel_;
    /**
     * <code>int32 unlockLevel = 7;</code>
     * @return The unlockLevel.
     */
    @java.lang.Override
    public int getUnlockLevel() {
      return unlockLevel_;
    }

    public static final int LEVELS_FIELD_NUMBER = 8;
    private java.util.List<com.widogame.minegamedataserver.grpc.SkillsMessage.Level> levels_;
    /**
     * <code>repeated .Level levels = 8;</code>
     */
    @java.lang.Override
    public java.util.List<com.widogame.minegamedataserver.grpc.SkillsMessage.Level> getLevelsList() {
      return levels_;
    }
    /**
     * <code>repeated .Level levels = 8;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.widogame.minegamedataserver.grpc.SkillsMessage.LevelOrBuilder> 
        getLevelsOrBuilderList() {
      return levels_;
    }
    /**
     * <code>repeated .Level levels = 8;</code>
     */
    @java.lang.Override
    public int getLevelsCount() {
      return levels_.size();
    }
    /**
     * <code>repeated .Level levels = 8;</code>
     */
    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.SkillsMessage.Level getLevels(int index) {
      return levels_.get(index);
    }
    /**
     * <code>repeated .Level levels = 8;</code>
     */
    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.SkillsMessage.LevelOrBuilder getLevelsOrBuilder(
        int index) {
      return levels_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (partId_ != 0) {
        output.writeInt32(2, partId_);
      }
      if (partType_ != 0) {
        output.writeInt32(3, partType_);
      }
      if (type_ != 0) {
        output.writeInt32(4, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
      }
      if (java.lang.Float.floatToRawIntBits(animDuration_) != 0) {
        output.writeFloat(6, animDuration_);
      }
      if (unlockLevel_ != 0) {
        output.writeInt32(7, unlockLevel_);
      }
      for (int i = 0; i < levels_.size(); i++) {
        output.writeMessage(8, levels_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (partId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, partId_);
      }
      if (partType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, partType_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
      }
      if (java.lang.Float.floatToRawIntBits(animDuration_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, animDuration_);
      }
      if (unlockLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, unlockLevel_);
      }
      for (int i = 0; i < levels_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, levels_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.widogame.minegamedataserver.grpc.SkillsMessage.Skills)) {
        return super.equals(obj);
      }
      com.widogame.minegamedataserver.grpc.SkillsMessage.Skills other = (com.widogame.minegamedataserver.grpc.SkillsMessage.Skills) obj;

      if (getId()
          != other.getId()) return false;
      if (getPartId()
          != other.getPartId()) return false;
      if (getPartType()
          != other.getPartType()) return false;
      if (getType()
          != other.getType()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (java.lang.Float.floatToIntBits(getAnimDuration())
          != java.lang.Float.floatToIntBits(
              other.getAnimDuration())) return false;
      if (getUnlockLevel()
          != other.getUnlockLevel()) return false;
      if (!getLevelsList()
          .equals(other.getLevelsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + PARTID_FIELD_NUMBER;
      hash = (53 * hash) + getPartId();
      hash = (37 * hash) + PARTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPartType();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ANIMDURATION_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAnimDuration());
      hash = (37 * hash) + UNLOCKLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getUnlockLevel();
      if (getLevelsCount() > 0) {
        hash = (37 * hash) + LEVELS_FIELD_NUMBER;
        hash = (53 * hash) + getLevelsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Skills parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Skills parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Skills parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Skills parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Skills parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Skills parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Skills parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Skills parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Skills parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Skills parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Skills parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Skills parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.widogame.minegamedataserver.grpc.SkillsMessage.Skills prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Skills}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Skills)
        com.widogame.minegamedataserver.grpc.SkillsMessage.SkillsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.widogame.minegamedataserver.grpc.SkillsMessage.internal_static_Skills_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.widogame.minegamedataserver.grpc.SkillsMessage.internal_static_Skills_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.class, com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.Builder.class);
      }

      // Construct using com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLevelsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        partId_ = 0;

        partType_ = 0;

        type_ = 0;

        name_ = "";

        animDuration_ = 0F;

        unlockLevel_ = 0;

        if (levelsBuilder_ == null) {
          levels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          levelsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.widogame.minegamedataserver.grpc.SkillsMessage.internal_static_Skills_descriptor;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Skills getDefaultInstanceForType() {
        return com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.getDefaultInstance();
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Skills build() {
        com.widogame.minegamedataserver.grpc.SkillsMessage.Skills result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Skills buildPartial() {
        com.widogame.minegamedataserver.grpc.SkillsMessage.Skills result = new com.widogame.minegamedataserver.grpc.SkillsMessage.Skills(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.partId_ = partId_;
        result.partType_ = partType_;
        result.type_ = type_;
        result.name_ = name_;
        result.animDuration_ = animDuration_;
        result.unlockLevel_ = unlockLevel_;
        if (levelsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            levels_ = java.util.Collections.unmodifiableList(levels_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.levels_ = levels_;
        } else {
          result.levels_ = levelsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.widogame.minegamedataserver.grpc.SkillsMessage.Skills) {
          return mergeFrom((com.widogame.minegamedataserver.grpc.SkillsMessage.Skills)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.widogame.minegamedataserver.grpc.SkillsMessage.Skills other) {
        if (other == com.widogame.minegamedataserver.grpc.SkillsMessage.Skills.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getPartId() != 0) {
          setPartId(other.getPartId());
        }
        if (other.getPartType() != 0) {
          setPartType(other.getPartType());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAnimDuration() != 0F) {
          setAnimDuration(other.getAnimDuration());
        }
        if (other.getUnlockLevel() != 0) {
          setUnlockLevel(other.getUnlockLevel());
        }
        if (levelsBuilder_ == null) {
          if (!other.levels_.isEmpty()) {
            if (levels_.isEmpty()) {
              levels_ = other.levels_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLevelsIsMutable();
              levels_.addAll(other.levels_);
            }
            onChanged();
          }
        } else {
          if (!other.levels_.isEmpty()) {
            if (levelsBuilder_.isEmpty()) {
              levelsBuilder_.dispose();
              levelsBuilder_ = null;
              levels_ = other.levels_;
              bitField0_ = (bitField0_ & ~0x00000001);
              levelsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLevelsFieldBuilder() : null;
            } else {
              levelsBuilder_.addAllMessages(other.levels_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.widogame.minegamedataserver.grpc.SkillsMessage.Skills parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.widogame.minegamedataserver.grpc.SkillsMessage.Skills) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int partId_ ;
      /**
       * <code>int32 partId = 2;</code>
       * @return The partId.
       */
      @java.lang.Override
      public int getPartId() {
        return partId_;
      }
      /**
       * <code>int32 partId = 2;</code>
       * @param value The partId to set.
       * @return This builder for chaining.
       */
      public Builder setPartId(int value) {
        
        partId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 partId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartId() {
        
        partId_ = 0;
        onChanged();
        return this;
      }

      private int partType_ ;
      /**
       * <code>int32 partType = 3;</code>
       * @return The partType.
       */
      @java.lang.Override
      public int getPartType() {
        return partType_;
      }
      /**
       * <code>int32 partType = 3;</code>
       * @param value The partType to set.
       * @return This builder for chaining.
       */
      public Builder setPartType(int value) {
        
        partType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 partType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartType() {
        
        partType_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 4;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 4;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 5;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 5;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 5;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 5;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private float animDuration_ ;
      /**
       * <code>float animDuration = 6;</code>
       * @return The animDuration.
       */
      @java.lang.Override
      public float getAnimDuration() {
        return animDuration_;
      }
      /**
       * <code>float animDuration = 6;</code>
       * @param value The animDuration to set.
       * @return This builder for chaining.
       */
      public Builder setAnimDuration(float value) {
        
        animDuration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float animDuration = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnimDuration() {
        
        animDuration_ = 0F;
        onChanged();
        return this;
      }

      private int unlockLevel_ ;
      /**
       * <code>int32 unlockLevel = 7;</code>
       * @return The unlockLevel.
       */
      @java.lang.Override
      public int getUnlockLevel() {
        return unlockLevel_;
      }
      /**
       * <code>int32 unlockLevel = 7;</code>
       * @param value The unlockLevel to set.
       * @return This builder for chaining.
       */
      public Builder setUnlockLevel(int value) {
        
        unlockLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 unlockLevel = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnlockLevel() {
        
        unlockLevel_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.widogame.minegamedataserver.grpc.SkillsMessage.Level> levels_ =
        java.util.Collections.emptyList();
      private void ensureLevelsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          levels_ = new java.util.ArrayList<com.widogame.minegamedataserver.grpc.SkillsMessage.Level>(levels_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.widogame.minegamedataserver.grpc.SkillsMessage.Level, com.widogame.minegamedataserver.grpc.SkillsMessage.Level.Builder, com.widogame.minegamedataserver.grpc.SkillsMessage.LevelOrBuilder> levelsBuilder_;

      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public java.util.List<com.widogame.minegamedataserver.grpc.SkillsMessage.Level> getLevelsList() {
        if (levelsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(levels_);
        } else {
          return levelsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public int getLevelsCount() {
        if (levelsBuilder_ == null) {
          return levels_.size();
        } else {
          return levelsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Level getLevels(int index) {
        if (levelsBuilder_ == null) {
          return levels_.get(index);
        } else {
          return levelsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public Builder setLevels(
          int index, com.widogame.minegamedataserver.grpc.SkillsMessage.Level value) {
        if (levelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLevelsIsMutable();
          levels_.set(index, value);
          onChanged();
        } else {
          levelsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public Builder setLevels(
          int index, com.widogame.minegamedataserver.grpc.SkillsMessage.Level.Builder builderForValue) {
        if (levelsBuilder_ == null) {
          ensureLevelsIsMutable();
          levels_.set(index, builderForValue.build());
          onChanged();
        } else {
          levelsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public Builder addLevels(com.widogame.minegamedataserver.grpc.SkillsMessage.Level value) {
        if (levelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLevelsIsMutable();
          levels_.add(value);
          onChanged();
        } else {
          levelsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public Builder addLevels(
          int index, com.widogame.minegamedataserver.grpc.SkillsMessage.Level value) {
        if (levelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLevelsIsMutable();
          levels_.add(index, value);
          onChanged();
        } else {
          levelsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public Builder addLevels(
          com.widogame.minegamedataserver.grpc.SkillsMessage.Level.Builder builderForValue) {
        if (levelsBuilder_ == null) {
          ensureLevelsIsMutable();
          levels_.add(builderForValue.build());
          onChanged();
        } else {
          levelsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public Builder addLevels(
          int index, com.widogame.minegamedataserver.grpc.SkillsMessage.Level.Builder builderForValue) {
        if (levelsBuilder_ == null) {
          ensureLevelsIsMutable();
          levels_.add(index, builderForValue.build());
          onChanged();
        } else {
          levelsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public Builder addAllLevels(
          java.lang.Iterable<? extends com.widogame.minegamedataserver.grpc.SkillsMessage.Level> values) {
        if (levelsBuilder_ == null) {
          ensureLevelsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, levels_);
          onChanged();
        } else {
          levelsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public Builder clearLevels() {
        if (levelsBuilder_ == null) {
          levels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          levelsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public Builder removeLevels(int index) {
        if (levelsBuilder_ == null) {
          ensureLevelsIsMutable();
          levels_.remove(index);
          onChanged();
        } else {
          levelsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Level.Builder getLevelsBuilder(
          int index) {
        return getLevelsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public com.widogame.minegamedataserver.grpc.SkillsMessage.LevelOrBuilder getLevelsOrBuilder(
          int index) {
        if (levelsBuilder_ == null) {
          return levels_.get(index);  } else {
          return levelsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public java.util.List<? extends com.widogame.minegamedataserver.grpc.SkillsMessage.LevelOrBuilder> 
           getLevelsOrBuilderList() {
        if (levelsBuilder_ != null) {
          return levelsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(levels_);
        }
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Level.Builder addLevelsBuilder() {
        return getLevelsFieldBuilder().addBuilder(
            com.widogame.minegamedataserver.grpc.SkillsMessage.Level.getDefaultInstance());
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Level.Builder addLevelsBuilder(
          int index) {
        return getLevelsFieldBuilder().addBuilder(
            index, com.widogame.minegamedataserver.grpc.SkillsMessage.Level.getDefaultInstance());
      }
      /**
       * <code>repeated .Level levels = 8;</code>
       */
      public java.util.List<com.widogame.minegamedataserver.grpc.SkillsMessage.Level.Builder> 
           getLevelsBuilderList() {
        return getLevelsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.widogame.minegamedataserver.grpc.SkillsMessage.Level, com.widogame.minegamedataserver.grpc.SkillsMessage.Level.Builder, com.widogame.minegamedataserver.grpc.SkillsMessage.LevelOrBuilder> 
          getLevelsFieldBuilder() {
        if (levelsBuilder_ == null) {
          levelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.widogame.minegamedataserver.grpc.SkillsMessage.Level, com.widogame.minegamedataserver.grpc.SkillsMessage.Level.Builder, com.widogame.minegamedataserver.grpc.SkillsMessage.LevelOrBuilder>(
                  levels_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          levels_ = null;
        }
        return levelsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Skills)
    }

    // @@protoc_insertion_point(class_scope:Skills)
    private static final com.widogame.minegamedataserver.grpc.SkillsMessage.Skills DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.widogame.minegamedataserver.grpc.SkillsMessage.Skills();
    }

    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Skills getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Skills>
        PARSER = new com.google.protobuf.AbstractParser<Skills>() {
      @java.lang.Override
      public Skills parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Skills(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Skills> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Skills> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.SkillsMessage.Skills getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LevelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Level)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float radius = 1;</code>
     * @return The radius.
     */
    float getRadius();

    /**
     * <code>float angle = 2;</code>
     * @return The angle.
     */
    float getAngle();

    /**
     * <code>float damage = 3;</code>
     * @return The damage.
     */
    float getDamage();

    /**
     * <code>float ttl = 4;</code>
     * @return The ttl.
     */
    float getTtl();

    /**
     * <code>float cooldown = 5;</code>
     * @return The cooldown.
     */
    float getCooldown();
  }
  /**
   * Protobuf type {@code Level}
   */
  public static final class Level extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Level)
      LevelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Level.newBuilder() to construct.
    private Level(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Level() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Level();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Level(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              radius_ = input.readFloat();
              break;
            }
            case 21: {

              angle_ = input.readFloat();
              break;
            }
            case 29: {

              damage_ = input.readFloat();
              break;
            }
            case 37: {

              ttl_ = input.readFloat();
              break;
            }
            case 45: {

              cooldown_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.widogame.minegamedataserver.grpc.SkillsMessage.internal_static_Level_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.widogame.minegamedataserver.grpc.SkillsMessage.internal_static_Level_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.widogame.minegamedataserver.grpc.SkillsMessage.Level.class, com.widogame.minegamedataserver.grpc.SkillsMessage.Level.Builder.class);
    }

    public static final int RADIUS_FIELD_NUMBER = 1;
    private float radius_;
    /**
     * <code>float radius = 1;</code>
     * @return The radius.
     */
    @java.lang.Override
    public float getRadius() {
      return radius_;
    }

    public static final int ANGLE_FIELD_NUMBER = 2;
    private float angle_;
    /**
     * <code>float angle = 2;</code>
     * @return The angle.
     */
    @java.lang.Override
    public float getAngle() {
      return angle_;
    }

    public static final int DAMAGE_FIELD_NUMBER = 3;
    private float damage_;
    /**
     * <code>float damage = 3;</code>
     * @return The damage.
     */
    @java.lang.Override
    public float getDamage() {
      return damage_;
    }

    public static final int TTL_FIELD_NUMBER = 4;
    private float ttl_;
    /**
     * <code>float ttl = 4;</code>
     * @return The ttl.
     */
    @java.lang.Override
    public float getTtl() {
      return ttl_;
    }

    public static final int COOLDOWN_FIELD_NUMBER = 5;
    private float cooldown_;
    /**
     * <code>float cooldown = 5;</code>
     * @return The cooldown.
     */
    @java.lang.Override
    public float getCooldown() {
      return cooldown_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(radius_) != 0) {
        output.writeFloat(1, radius_);
      }
      if (java.lang.Float.floatToRawIntBits(angle_) != 0) {
        output.writeFloat(2, angle_);
      }
      if (java.lang.Float.floatToRawIntBits(damage_) != 0) {
        output.writeFloat(3, damage_);
      }
      if (java.lang.Float.floatToRawIntBits(ttl_) != 0) {
        output.writeFloat(4, ttl_);
      }
      if (java.lang.Float.floatToRawIntBits(cooldown_) != 0) {
        output.writeFloat(5, cooldown_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(radius_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, radius_);
      }
      if (java.lang.Float.floatToRawIntBits(angle_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, angle_);
      }
      if (java.lang.Float.floatToRawIntBits(damage_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, damage_);
      }
      if (java.lang.Float.floatToRawIntBits(ttl_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, ttl_);
      }
      if (java.lang.Float.floatToRawIntBits(cooldown_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, cooldown_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.widogame.minegamedataserver.grpc.SkillsMessage.Level)) {
        return super.equals(obj);
      }
      com.widogame.minegamedataserver.grpc.SkillsMessage.Level other = (com.widogame.minegamedataserver.grpc.SkillsMessage.Level) obj;

      if (java.lang.Float.floatToIntBits(getRadius())
          != java.lang.Float.floatToIntBits(
              other.getRadius())) return false;
      if (java.lang.Float.floatToIntBits(getAngle())
          != java.lang.Float.floatToIntBits(
              other.getAngle())) return false;
      if (java.lang.Float.floatToIntBits(getDamage())
          != java.lang.Float.floatToIntBits(
              other.getDamage())) return false;
      if (java.lang.Float.floatToIntBits(getTtl())
          != java.lang.Float.floatToIntBits(
              other.getTtl())) return false;
      if (java.lang.Float.floatToIntBits(getCooldown())
          != java.lang.Float.floatToIntBits(
              other.getCooldown())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RADIUS_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getRadius());
      hash = (37 * hash) + ANGLE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAngle());
      hash = (37 * hash) + DAMAGE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDamage());
      hash = (37 * hash) + TTL_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTtl());
      hash = (37 * hash) + COOLDOWN_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCooldown());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Level parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Level parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Level parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Level parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Level parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Level parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Level parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Level parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Level parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Level parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Level parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Level parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.widogame.minegamedataserver.grpc.SkillsMessage.Level prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Level}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Level)
        com.widogame.minegamedataserver.grpc.SkillsMessage.LevelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.widogame.minegamedataserver.grpc.SkillsMessage.internal_static_Level_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.widogame.minegamedataserver.grpc.SkillsMessage.internal_static_Level_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.widogame.minegamedataserver.grpc.SkillsMessage.Level.class, com.widogame.minegamedataserver.grpc.SkillsMessage.Level.Builder.class);
      }

      // Construct using com.widogame.minegamedataserver.grpc.SkillsMessage.Level.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        radius_ = 0F;

        angle_ = 0F;

        damage_ = 0F;

        ttl_ = 0F;

        cooldown_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.widogame.minegamedataserver.grpc.SkillsMessage.internal_static_Level_descriptor;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Level getDefaultInstanceForType() {
        return com.widogame.minegamedataserver.grpc.SkillsMessage.Level.getDefaultInstance();
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Level build() {
        com.widogame.minegamedataserver.grpc.SkillsMessage.Level result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.widogame.minegamedataserver.grpc.SkillsMessage.Level buildPartial() {
        com.widogame.minegamedataserver.grpc.SkillsMessage.Level result = new com.widogame.minegamedataserver.grpc.SkillsMessage.Level(this);
        result.radius_ = radius_;
        result.angle_ = angle_;
        result.damage_ = damage_;
        result.ttl_ = ttl_;
        result.cooldown_ = cooldown_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.widogame.minegamedataserver.grpc.SkillsMessage.Level) {
          return mergeFrom((com.widogame.minegamedataserver.grpc.SkillsMessage.Level)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.widogame.minegamedataserver.grpc.SkillsMessage.Level other) {
        if (other == com.widogame.minegamedataserver.grpc.SkillsMessage.Level.getDefaultInstance()) return this;
        if (other.getRadius() != 0F) {
          setRadius(other.getRadius());
        }
        if (other.getAngle() != 0F) {
          setAngle(other.getAngle());
        }
        if (other.getDamage() != 0F) {
          setDamage(other.getDamage());
        }
        if (other.getTtl() != 0F) {
          setTtl(other.getTtl());
        }
        if (other.getCooldown() != 0F) {
          setCooldown(other.getCooldown());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.widogame.minegamedataserver.grpc.SkillsMessage.Level parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.widogame.minegamedataserver.grpc.SkillsMessage.Level) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float radius_ ;
      /**
       * <code>float radius = 1;</code>
       * @return The radius.
       */
      @java.lang.Override
      public float getRadius() {
        return radius_;
      }
      /**
       * <code>float radius = 1;</code>
       * @param value The radius to set.
       * @return This builder for chaining.
       */
      public Builder setRadius(float value) {
        
        radius_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float radius = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRadius() {
        
        radius_ = 0F;
        onChanged();
        return this;
      }

      private float angle_ ;
      /**
       * <code>float angle = 2;</code>
       * @return The angle.
       */
      @java.lang.Override
      public float getAngle() {
        return angle_;
      }
      /**
       * <code>float angle = 2;</code>
       * @param value The angle to set.
       * @return This builder for chaining.
       */
      public Builder setAngle(float value) {
        
        angle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float angle = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAngle() {
        
        angle_ = 0F;
        onChanged();
        return this;
      }

      private float damage_ ;
      /**
       * <code>float damage = 3;</code>
       * @return The damage.
       */
      @java.lang.Override
      public float getDamage() {
        return damage_;
      }
      /**
       * <code>float damage = 3;</code>
       * @param value The damage to set.
       * @return This builder for chaining.
       */
      public Builder setDamage(float value) {
        
        damage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float damage = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDamage() {
        
        damage_ = 0F;
        onChanged();
        return this;
      }

      private float ttl_ ;
      /**
       * <code>float ttl = 4;</code>
       * @return The ttl.
       */
      @java.lang.Override
      public float getTtl() {
        return ttl_;
      }
      /**
       * <code>float ttl = 4;</code>
       * @param value The ttl to set.
       * @return This builder for chaining.
       */
      public Builder setTtl(float value) {
        
        ttl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float ttl = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTtl() {
        
        ttl_ = 0F;
        onChanged();
        return this;
      }

      private float cooldown_ ;
      /**
       * <code>float cooldown = 5;</code>
       * @return The cooldown.
       */
      @java.lang.Override
      public float getCooldown() {
        return cooldown_;
      }
      /**
       * <code>float cooldown = 5;</code>
       * @param value The cooldown to set.
       * @return This builder for chaining.
       */
      public Builder setCooldown(float value) {
        
        cooldown_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float cooldown = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCooldown() {
        
        cooldown_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Level)
    }

    // @@protoc_insertion_point(class_scope:Level)
    private static final com.widogame.minegamedataserver.grpc.SkillsMessage.Level DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.widogame.minegamedataserver.grpc.SkillsMessage.Level();
    }

    public static com.widogame.minegamedataserver.grpc.SkillsMessage.Level getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Level>
        PARSER = new com.google.protobuf.AbstractParser<Level>() {
      @java.lang.Override
      public Level parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Level(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Level> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Level> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.widogame.minegamedataserver.grpc.SkillsMessage.Level getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Skills_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Skills_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Level_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Level_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034messages/SkillsMessage.proto\"\225\001\n\006Skill" +
      "s\022\n\n\002id\030\001 \001(\005\022\016\n\006partId\030\002 \001(\005\022\020\n\010partTyp" +
      "e\030\003 \001(\005\022\014\n\004type\030\004 \001(\005\022\014\n\004name\030\005 \001(\t\022\024\n\014a" +
      "nimDuration\030\006 \001(\002\022\023\n\013unlockLevel\030\007 \001(\005\022\026" +
      "\n\006levels\030\010 \003(\0132\006.Level\"U\n\005Level\022\016\n\006radiu" +
      "s\030\001 \001(\002\022\r\n\005angle\030\002 \001(\002\022\016\n\006damage\030\003 \001(\002\022\013" +
      "\n\003ttl\030\004 \001(\002\022\020\n\010cooldown\030\005 \001(\002B\\\n$com.wid" +
      "ogame.minegamedataserver.grpcB\rSkillsMes" +
      "sage\252\002$com.widogame.minegamedataserver.g" +
      "rpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Skills_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Skills_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Skills_descriptor,
        new java.lang.String[] { "Id", "PartId", "PartType", "Type", "Name", "AnimDuration", "UnlockLevel", "Levels", });
    internal_static_Level_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Level_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Level_descriptor,
        new java.lang.String[] { "Radius", "Angle", "Damage", "Ttl", "Cooldown", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
